// Command corpusgen builds the reusable accuracy corpus from canonical rule
// fixtures. It is intentionally dependency-free and deterministic.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type specFile struct {
	Rules []specRule `json:"rules"`
}
type specRule struct {
	ID       string `json:"id"`
	Fixtures struct {
		Match   []string `json:"match"`
		NoMatch []string `json:"nomatch"`
	} `json:"fixtures"`
}

var formats = []string{
	"FormatAgentJSON", "FormatAgentJSONL", "FormatShell", "FormatGitDiff",
	"FormatEnv", "FormatHTTPRequest", "FormatHTTPResponse", "FormatMinified",
	"FormatEscaped", "FormatAdversarial",
}

func main() {
	paths, err := filepath.Glob(filepath.Join("..", "rules", "specs", "*.json"))
	if err != nil {
		panic(err)
	}
	var rules []specRule
	for _, path := range paths {
		data, err := os.ReadFile(path)
		if err != nil {
			panic(err)
		}
		var sf specFile
		if err := json.Unmarshal(data, &sf); err != nil {
			panic(fmt.Errorf("%s: %w", path, err))
		}
		rules = append(rules, sf.Rules...)
	}
	sort.Slice(rules, func(i, j int) bool { return rules[i].ID < rules[j].ID })
	var b bytes.Buffer
	b.WriteString("// Code generated by corpusgen from internal/rules/specs. DO NOT EDIT.\n\npackage accuracy\n\nvar generatedCorpus = []Fixture{\n")
	formatIndex := 0
	for _, rule := range rules {
		for _, group := range []struct {
			positive bool
			values   []string
		}{{true, rule.Fixtures.Match}, {false, rule.Fixtures.NoMatch}} {
			for i, value := range group.values {
				fmt.Fprintf(&b, "{RuleID: %s, Positive: %t, Ordinal: %d, Format: %s, Value: %s},\n", strconv.Quote(rule.ID), group.positive, i, formats[formatIndex%len(formats)], strconv.Quote(value))
				formatIndex++
			}
		}
	}
	// Add one positive and negative document in each required transport
	// format. The short negative deliberately resembles the positive prefix.
	for i, formatName := range formats {
		for _, scenario := range []struct {
			positive bool
			value    string
		}{{true, "ghp_16C7e42F292c6912E7710c838347Ae178B4a"}, {false, "ghp_short"}} {
			value := formattedDocument(formatName, scenario.value)
			fmt.Fprintf(&b, "{RuleID: %q, Positive: %t, Ordinal: %d, Format: %s, Value: %s},\n", "github-pat", scenario.positive, 1000+i, formatName, strconv.Quote(value))
		}
	}
	b.WriteString("}\n")
	source, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("zz_generated_corpus.go", source, 0o644); err != nil {
		panic(err)
	}
}

func formattedDocument(formatName, value string) string {
	switch formatName {
	case "FormatAgentJSON":
		return `{"session":{"tool_output":` + strconv.Quote(value) + `}}`
	case "FormatAgentJSONL":
		return `{"type":"message","content":` + strconv.Quote(value) + "}\n"
	case "FormatShell":
		return "$ printenv TOKEN\n" + value + "\n"
	case "FormatGitDiff":
		return "diff --git a/.env b/.env\n@@ -0,0 +1 @@\n+TOKEN=" + value + "\n"
	case "FormatEnv":
		return "SHELL=/bin/sh\nTOKEN=" + value + "\nTERM=dumb\n"
	case "FormatHTTPRequest":
		return "GET / HTTP/1.1\nHost: example.invalid\nX-Token: " + value + "\n\n"
	case "FormatHTTPResponse":
		return "HTTP/1.1 200 OK\nX-Token: " + value + "\n\n"
	case "FormatMinified":
		return `{"token":` + strconv.Quote(value) + `,"ok":true}`
	case "FormatEscaped":
		return strings.ReplaceAll(strconv.Quote("token="+value), `=`, `\u003d`)
	case "FormatAdversarial":
		return "token password secret credential authorization api_key harmless :: " + value
	default:
		panic("unknown format " + formatName)
	}
}
