// Code generated by rulegen from internal/rules/specs. DO NOT EDIT.

package rules

import "github.com/lastpersonlabs/goredact/internal/rules/validators"

// Version identifies the built-in rule-set revision. It is the first 12
// hex characters of the SHA-256 digest of the canonical serialization of
// the generated rule table below (see tools/rulegen), so it changes
// exactly when the generated rules change.
const Version = "builtin-d69c0cddd01e"

func init() {
	RegisterBuiltins([]Rule{
		{
			ID:   "github-pat",
			Name: "GitHub personal access token",
			Triggers: []Trigger{
				{Literal: "ghp_", CaseFold: false},
			},
			Validate:      validators.GitHubPAT,
			MinProfile:    ProfileFast,
			Confidence:    ConfidenceHigh,
			MaxLookbehind: 0,
			MaxLookahead:  64,
		},
		{
			ID:   "slack-bot-token",
			Name: "Slack bot token",
			Triggers: []Trigger{
				{Literal: "xoxb-", CaseFold: false},
			},
			Validate:      validators.SlackBotToken,
			MinProfile:    ProfileFast,
			Confidence:    ConfidenceHigh,
			MaxLookbehind: 0,
			MaxLookahead:  96,
		},
	})
}
