// Code generated by rulegen from internal/rules/specs. DO NOT EDIT.
//
// Provenance:
//   github-pat: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats (original)
//   slack-bot-token: https://api.slack.com/authentication/token-types#bot (original)

package rules

import "testing"

// TestGeneratedRuleFixtures confirms that every match fixture in
// internal/rules/specs is confirmed by its rule's Validate at some trigger
// occurrence, and that every nomatch fixture is confirmed at none.
func TestGeneratedRuleFixtures(t *testing.T) {
	cases := []struct {
		id      string
		match   []string
		nomatch []string
	}{
		{
			id:      "github-pat",
			match:   []string{"ghp_16C7e42F292c6912E7710c838347Ae178B4a", "ghp_OhbVrpoiVgRV5IfLBcbfnoGMbJmTPSIAoCLr"},
			nomatch: []string{"ghp_short", "ghp_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "ghp_u8jzPde0IgxLd6GncfBAepfJBd0Kh8oOOL8dA"},
		},
		{
			id:      "slack-bot-token",
			match:   []string{"xoxb-0265423511615-5940781618495-KmTecQoXsf2o3gyrDO1xkxwnQrS7RP"},
			nomatch: []string{"xoxb-123-456-abcdefgh", "xoxb-0265423511615-5940781618495-aaaaaaaaaaaaaaaaaaaaaaaaaaaa", "xoxb-99603082462819-48219935181-KdNnFRIBXuDL7DxtpYlSXpfKtHF4"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.id, func(t *testing.T) {
			rule, ok := generatedFixtureRule(tc.id)
			if !ok {
				t.Fatalf("rule %q not registered in Builtins()", tc.id)
			}
			for _, fx := range tc.match {
				if !generatedFixtureConfirms(rule, fx) {
					t.Errorf("rule %q: match fixture %q: want a trigger occurrence to validate, none did", tc.id, fx)
				}
			}
			for _, fx := range tc.nomatch {
				if generatedFixtureConfirms(rule, fx) {
					t.Errorf("rule %q: nomatch fixture %q: want no trigger occurrence to validate, one did", tc.id, fx)
				}
			}
		})
	}
}

// generatedFixtureRule, generatedFixtureConfirms, and their helpers below
// are static: their code does not depend on the specs, only on the
// (id, match, nomatch) table above, so they are byte-identical across
// regenerations that don't change the rulegen version.

func generatedFixtureRule(id string) (Rule, bool) {
	for _, r := range Builtins() {
		if r.ID == id {
			return r, true
		}
	}
	return Rule{}, false
}

// generatedFixtureConfirms reports whether at least one occurrence of one
// of rule's triggers within data is confirmed by rule.Validate, using the
// window rule.MaxLookbehind/MaxLookahead would produce at that offset
// (clamped to data's bounds).
func generatedFixtureConfirms(rule Rule, data string) bool {
	b := []byte(data)
	for _, trig := range rule.Triggers {
		for _, occ := range generatedFindOccurrences(b, trig) {
			lo := occ.start - rule.MaxLookbehind
			if lo < 0 {
				lo = 0
			}
			hi := occ.end + rule.MaxLookahead
			if hi > len(b) {
				hi = len(b)
			}
			window := b[lo:hi]
			ts, te := occ.start-lo, occ.end-lo
			if _, _, ok := rule.Validate(window, ts, te); ok {
				return true
			}
		}
	}
	return false
}

type generatedOccurrence struct{ start, end int }

// generatedFindOccurrences returns every occurrence (including overlapping
// ones) of trig.Literal in data, honoring trig.CaseFold with the ASCII
// case folding rule from docs/DESIGN.md (fold 'A'-'Z' to lowercase on both
// sides).
func generatedFindOccurrences(data []byte, trig Trigger) []generatedOccurrence {
	lit := []byte(trig.Literal)
	if len(lit) == 0 || len(lit) > len(data) {
		return nil
	}
	var out []generatedOccurrence
	for i := 0; i+len(lit) <= len(data); i++ {
		if generatedASCIIEqualFold(data[i:i+len(lit)], lit, trig.CaseFold) {
			out = append(out, generatedOccurrence{start: i, end: i + len(lit)})
		}
	}
	return out
}

func generatedASCIIEqualFold(a, b []byte, caseFold bool) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		ac, bc := a[i], b[i]
		if caseFold {
			ac = generatedASCIIFoldByte(ac)
			bc = generatedASCIIFoldByte(bc)
		}
		if ac != bc {
			return false
		}
	}
	return true
}

func generatedASCIIFoldByte(c byte) byte {
	if c >= 'A' && c <= 'Z' {
		return c - 'A' + 'a'
	}
	return c
}
