// Code generated by rulegen from internal/rules/specs. DO NOT EDIT.
//
// Provenance:
//   anthropic-api-key: https://docs.anthropic.com/en/api/getting-started (original)
//   authorization-bearer: ENG-100 contextual header detection; scheme grammar per RFC 6750 (Bearer), RFC 7617 (Basic), AWS SigV4 Authorization header (original)
//   aws-access-key-id: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-unique-ids (original)
//   aws-secret-access-key: https://docs.aws.amazon.com/general/latest/gr/aws-access-keys-best-practices.html (original)
//   azure-storage-account-key: https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage (original)
//   command-line-password-flag: ENG-100 contextual CLI flag detection (internal design, no single external spec) (original)
//   cookie-session-token: ENG-100 contextual cookie detection; pair grammar per RFC 6265 (HTTP State Management Mechanism) (original)
//   dockerhub-pat: https://docs.docker.com/security/for-developers/access-tokens/ (original)
//   gcp-api-key: https://cloud.google.com/docs/authentication/api-keys (original)
//   generic-api-key-assignment: ENG-98 contextual entropy detection: assignment-style generic credential heuristic (internal design, no single external spec) (original)
//   generic-bearer-like-token-assignment: ENG-98 contextual entropy detection: assignment-style generic credential heuristic (internal design, no single external spec) (original)
//   generic-password-assignment: ENG-98 contextual entropy detection: assignment-style generic credential heuristic (internal design, no single external spec) (original)
//   github-app-token: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats (original)
//   github-fine-grained-pat: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats (original)
//   github-oauth-token: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats (original)
//   github-pat: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats (original)
//   github-refresh-token: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats (original)
//   gitlab-deploy-token: https://docs.gitlab.com/user/project/deploy_tokens/ (original)
//   gitlab-pat: https://docs.gitlab.com/user/profile/personal_access_tokens/#create-a-personal-access-token (original)
//   gitlab-runner-token: https://docs.gitlab.com/ci/runners/new_creation_workflow/#glrt-authentication-tokens (original)
//   groq-api-key: https://console.groq.com/docs/api-keys (original)
//   huggingface-token: https://huggingface.co/docs/hub/security-tokens (original)
//   linear-api-key: https://developers.linear.app/docs/graphql/working-with-the-graphql-api#personal-api-keys (original)
//   notion-internal-token: https://developers.notion.com/docs/authorization (original)
//   npm-access-token: https://docs.npmjs.com/about-access-tokens (original)
//   openai-legacy-key: https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety (original)
//   openai-project-key: https://help.openai.com/en/articles/9186755-managing-your-work-in-the-api-platform-with-projects (original)
//   pem-private-key: https://datatracker.ietf.org/doc/html/rfc7468 (original)
//   putty-private-key: https://tartarus.org/~simon/putty-snapshots/htmldoc/AppendixC.html (original)
//   pypi-api-token: https://docs.pypi.org/api/token/ (original)
//   sendgrid-api-key: https://docs.sendgrid.com/ui/account-and-settings/api-keys (original)
//   slack-app-token: https://api.slack.com/authentication/token-types#app-level (original)
//   slack-bot-token: https://api.slack.com/authentication/token-types#bot (original)
//   slack-user-token: https://api.slack.com/authentication/token-types#user (original)
//   stripe-secret-key: https://docs.stripe.com/keys (original)
//   stripe-webhook-secret: https://docs.stripe.com/webhooks#verify-official-libraries (original)
//   twilio-api-key-sid: https://www.twilio.com/docs/iam/api-keys (original)
//   url-credentials: ENG-100 contextual URL detection; userinfo grammar per RFC 3986 section 3.2.1 (original)

package rules

import "testing"

// TestGeneratedRuleFixtures confirms that every match fixture in
// internal/rules/specs is confirmed by its rule's Validate at some trigger
// occurrence, and that every nomatch fixture is confirmed at none.
func TestGeneratedRuleFixtures(t *testing.T) {
	cases := []struct {
		id      string
		match   []string
		nomatch []string
	}{
		{
			id:      "anthropic-api-key",
			match:   []string{"Authorization: Bearer sk-ant-api03-L6VtNHDzbvOYIs52KThe1DBzYMxIsTnjxqnzKJgS1niDgzJKhy20RHoBqBbuVcPjhcUAwu89LeznSyn2bpa26sQIrfAA", "ANTHROPIC_API_KEY=sk-ant-admin01-V9AoHGzkZ5UL5o2kDCaFfewEFjXIn7vunFmrPxZZ28kDnJnDY4XLZ6XJmYO2aYzQMmLdhMAA83LqYzEQa8qbJ", "{\"config\": {\"anthropic_api_key\": \"sk-ant-api03-L6VtNHDzbvOYIs52KThe1DBzYMxIsTnjxqnzKJgS1niDgzJKhy20RHoBqBbuVcPjhcUAwu89LeznSyn2bpa26sQIrfAA\"}}"},
			nomatch: []string{"sk-ant-api03-short", "ANTHROPIC_API_KEY=sk-ant-xxxxxxxx…", "sk-ant-api03-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "The zoo increased its risk-ant-eater enclosure budget this year."},
		},
		{
			id:      "authorization-bearer",
			match:   []string{"GET /v1/orders HTTP/1.1\nHost: api.example.com\nAuthorization: Bearer kJ8vQ2mZ7xW4pL9sN3tYbF6hR0cD5gU1aE\nAccept: */*\n", "curl -H 'Proxy-Authorization: Bearer nQ7wL4mX8pZ1sT6bK3jH0cV5yR2dF9gA' https://api.example.com/v1", "{\"event\":\"http\",\"line\":\"\\\"authorization: bearer eyJhbGciOiJIUzI1NiJ9.pZ8kQ2vR7wL4mN0pX1sT.hB3jF6hZ1cYdA0eBqG\\\"\"}", "Authorization: Basic c3ZjLXVzZXI6a0o4dlEybVo3eFc0cEw5cw==", "Authorization: AWS4-HMAC-SHA256 Credential=AKIAUJZDEGXDNCF32EPF/20260810/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=7f3a92c1e8b4d06f5a2c9e17b3d84f60a1c5e29b7d4f18a3c6e05b92d7f41a8c"},
			nomatch: []string{"Authorization: Bearer <token>", "Authorization: Bearer ${API_TOKEN}", "# example: Authorization: Bearer YOUR-TOKEN-HERE-1234", "Authorization: Basic dXNlcjE=", "Authorization: Digest username=\"user1\", realm=\"api\", nonce=\"dcd98b7102dd2f0e\", response=\"6629fae49393a05397450978507c4ef1\"", "authorization: bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "aws-access-key-id",
			match:   []string{"AWS_ACCESS_KEY_ID=AKIAUJZDEGXDNCF32EPF", "{\"accessKeyId\": \"ASIA3DHODZDOCIS2JHTL\", \"region\": \"us-east-1\"}", "aws configure set aws_access_key_id ACCAGMXGEDN73U55XTPL"},
			nomatch: []string{"AWS_ACCESS_KEY_ID=AKIASHORT", "AWS_ACCESS_KEY_ID=AKIAujzdegxdncf32epf", "AWS_ACCESS_KEY_ID=XAKIAUJZDEGXDNCF32EPF", "AWS_ACCESS_KEY_ID=AKIAUJZDEGXDNCF32EPF9", "# example from the AWS docs: AKIAIOSFODNN7EXAMPLE"},
		},
		{
			id:      "aws-secret-access-key",
			match:   []string{"AWS_SECRET_ACCESS_KEY=fKm/r5kJP1VrT+1FJors/6ILi8IHn5kxsC7tVO/H", "aws_secret_access_key: bkQfyy/KV5zjR3j1twdTKWTddB+XhkAS1voQG6yy", "aws_secret_access_key = 'fKm/r5kJP1VrT+1FJors/6ILi8IHn5kxsC7tVO/H'"},
			nomatch: []string{"AWS_SECRET_ACCESS_KEY=tooshort", "AWS_SECRET_ACCESS_KEY aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "AWS_SECRET_ACCESS_KEY=fKm/r5kJP1VrT+1FJors/6ILi8IHn5kxsC7tVO/!", "aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"},
		},
		{
			id:      "azure-storage-account-key",
			match:   []string{"DefaultEndpointsProtocol=https;AccountName=contosostorage;AccountKey=5suKcNd8Zra9A9sKPxZ9W3qLy7zKUVQDT7S8sTQCBNR3YbDgbleph1QHt61QTC4XATWS8PHp9NHfYjFM5DI4pZ==;EndpointSuffix=core.windows.net", "AZURE_STORAGE_ACCOUNT_KEY=\"AccountKey=j59fhZ5R1Py4oJe2JbmPTuSgR7cMy+UcU3zr1ZtoLuCr64CxqlIOdNKhiFXiQ2hzT/pLjHX2JiCLhKcIhP6Br1==\""},
			nomatch: []string{"AccountKey=tooshort==", "AccountKey=5suKcNd8Zra9A9sKPxZ9W3qLy7zKUVQDT7S8sTQCBNR3YbDgbleph1QHt61QTC4XATWS8PHp9NHfYjFM5DI4pZ", "AccountKey=5suKcNd8Zra9A9sKPxZ9W3qLy7zKUVQDT7S8sTQCBNR3YbDgbleph1QHt61QTC4XATWS8PHp9NHfYjFM5DI4pZ!!", "AccountKey=5suKcNd8Zra9A9sKPxZ9W3qLy7zKUVQDT7S8sTQCBNR3YbDgbleph1QHt61QTC4XATWS8PHp9NHfYjFM5DI4pZ===extra"},
		},
		{
			id:      "command-line-password-flag",
			match:   []string{"mysql -h db.prod.internal -u app --password=tR8kW3nQ7zXm2 app_db", "vault login --token=hvs.9kQ3vR7wL4mN2xT6bF0jH5cD", "deploy --api-key 'Zp8kQ3vR7wL4mN2xT6bF9jH0' --env prod", "{\"cmd\":\"pg_restore --passwd=Xq7Lm2Vt9zR4 -d app\"}"},
			nomatch: []string{"pg_dump --password-file /run/secrets/pgpass -h db", "fetch --token-url https://auth.example.com/oauth/token", "mysql --password= --host db.internal", "run.sh --password ${DB_PASSWORD}", "docs: use --api-key <your-key> to authenticate", "login --secret changeme --user svc"},
		},
		{
			id:      "cookie-session-token",
			match:   []string{"Cookie: theme=dark; sessionid=aK9mQ2vR7wL4mN8pX1sTbF3j; lang=en", "Set-Cookie: sid=xT4bK9mQ2vR7wL0pZ8sN3jH6cY1dF5gA; Path=/; HttpOnly; Secure", "{\"headers\":{\"cookie\":\"gw_route=blue; auth_token=Zp8kQ3vR7wL4mN2xT6bF9jH0cD5yU1aE; region=eu\"}}", "{\"line\":\"\\\"cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.t8ZkQ2vRwLmN4xB7\\\"\"}"},
			nomatch: []string{"Cookie: theme=dark; lang=en; tz=UTC", "Cookie: sessionid=short1; theme=dark", "Set-Cookie: csrftoken=Qw8kV3nR7wL4mN2xT6bF9jH0cD5yU1aE; Path=/", "GET /cb?next=%2Fdash&token=aK9mQ2vR7wL4mN8pX1sTbF3j HTTP/1.1", "Cookie: session=<session-token>; theme=dark", "Cookie: auth=xxxxxxxxxxxxxxxxxxxx; theme=dark"},
		},
		{
			id:      "dockerhub-pat",
			match:   []string{"DOCKERHUB_PAT=dckr_pat_lBYwwQKx2h3qd82R5DtSx3oPE2-xPo0csQ6U", "{\"password\": \"dckr_pat_BMjUC6unM5EYWsQJ8jXp5k_KVfOY\"}"},
			nomatch: []string{"dckr_pat_short12345", "dckr_pat_abcDE12345 lBYwwQKx2h3qd82R5DtSx3oPE2-xPo0csQ6U", "dckr_pat_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "gcp-api-key",
			match:   []string{"GOOGLE_API_KEY=AIzazyN9zHYIa4UOrGNATMuDJawTgsu8PO_799n", "{\"apiKey\": \"AIzaKSNrh9UCauSDmLhuVtcqcYezdZ-tDDj8hYs\", \"authDomain\": \"example.firebaseapp.com\"}"},
			nomatch: []string{"GOOGLE_API_KEY=AIzatooshort", "GOOGLE_API_KEY=AIza!zyN9zHYIa4UOrGNATMuDJawTgsu8PO_799n", "GOOGLE_API_KEY=xAIzazyN9zHYIa4UOrGNATMuDJawTgsu8PO_799n", "GOOGLE_API_KEY=AIzaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},
		},
		{
			id:      "generic-api-key-assignment",
			match:   []string{"export API_KEY=sk_live_9fQ2vR7wL4mN8pX1sT6bF3jH0cD5yUaZ9k", "api_key: \"aZ9kQ2vR7wL4mN8pX1sT6bF3jH0cD5yU\"", "{\"access_token\": \"Xk9mP2vQ7Rt4Ws8LbN3jF6hZ1cYdA0eB5g\"}"},
			nomatch: []string{"api_key = \"your-api-key-here-1234567890\"", "client_secret: \"550e8400-e29b-41d4-a716-446655440000\"", "secret_key = \"hello_world_this_is_config\"", "capi_key = \"randomsecretvalueXk9mP2vQ7Rt4Ws8\""},
		},
		{
			id:      "generic-bearer-like-token-assignment",
			match:   []string{"export TOKEN=aZ9kQ2vR7wL4mN8pX1sT6bF3jH0cD5yUaZ9k", "token: \"Xk9mP2vQ7Rt4Ws8LbN3jF6hZ1cYdA0eB5gC7h\"", "{\"auth_token\": \"k3JmQz9XpL2vN7wR5tY8bC1sD4fA6hE0uI2oP\"}"},
			nomatch: []string{"token = csv.next()", "token: <YOUR_TOKEN>", "token = \"your-token-here-1234567890abcdef\"", "token: \"550e8400-e29b-41d4-a716-446655440000\"", "token = \"helloworldconfigurationvalue\""},
		},
		{
			id:      "generic-password-assignment",
			match:   []string{"export PASSWORD=Xk9mP2vQ7Rt4Ws8Lb", "password: \"Zt7Qp2Xk9mLwR4vN8\"", "{\"pwd\": \"aZ9kQ2vR7wL4mN8pX1sT6bF3\"}"},
			nomatch: []string{"password = \"changeme\"", "passwd: \"550e8400-e29b-41d4-a716-446655440000\"", "password = \"configuration\"", "pwd", "$ pwd", "passwd: files systemd"},
		},
		{
			id:      "github-app-token",
			match:   []string{"GITHUB_APP_USER_TOKEN=ghu_TD7USV0nSe6MVhPyD4v3RhFfioL0bco9gSiM", "installation_token: ghs_9b3mUXozvaTiZ0b6kg5jhePWvxPd3mLqzu8N"},
			nomatch: []string{"ghu_tooShort", "ghs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "ghu_TD7USV0nSe6MVhPyD4v3RhFfioL0bco9gSiM1"},
		},
		{
			id:      "github-fine-grained-pat",
			match:   []string{"GITHUB_FINE_GRAINED_PAT=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", "export TOKEN=\"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\""},
			nomatch: []string{"github_pat_pNLXUQBEWt9iBIWhqsMcTQ_short", "github_pat_pNLXUQBEWt9iBIWhqsMcTQ-iT0f4QyUrymftnlmT2umhmf7J6BgIuQ3ynO4SNP6dVUK0CcwZUvP8pmGW9F", "github_pat_xxxxxxxxxxxxxxxxxxxxxx_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "github-oauth-token",
			match:   []string{"GITHUB_OAUTH_TOKEN=gho_L2m69I7wDdQGnMo6sFSYnvCeqmkfCXIxmEYu", "{\"access_token\": \"gho_jRNwkJTQMlysNBKLcUHINVH44lVYyCoGifZd\", \"token_type\": \"bearer\"}"},
			nomatch: []string{"GITHUB_OAUTH_TOKEN=gho_tooShort123", "GITHUB_OAUTH_TOKEN=gho_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "GITHUB_OAUTH_TOKEN=gho_L2m69I7wDdQGnMo6sFSY nvCeqmkfCXIxmEYu"},
		},
		{
			id:      "github-pat",
			match:   []string{"ghp_16C7e42F292c6912E7710c838347Ae178B4a", "ghp_OhbVrpoiVgRV5IfLBcbfnoGMbJmTPSIAoCLr"},
			nomatch: []string{"ghp_short", "ghp_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "ghp_u8jzPde0IgxLd6GncfBAepfJBd0Kh8oOOL8dA"},
		},
		{
			id:      "github-refresh-token",
			match:   []string{"GITHUB_REFRESH_TOKEN=ghr_4LwLYg8atHXKvsk2wkW4jgQzw7k2BNy1DF43", "{\"refresh_token\":\"ghr_T5EbJ8H0Ed9ZqZemZFxBCVPsSoVDrTEPilrx\"}"},
			nomatch: []string{"GITHUB_REFRESH_TOKEN=ghr_short", "GITHUB_REFRESH_TOKEN=ghr_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "GITHUB_REFRESH_TOKEN=ghr_4LwLYg8atHXKvsk2wk W4jgQzw7k2BNy1DF43"},
		},
		{
			id:      "gitlab-deploy-token",
			match:   []string{"DEPLOY_TOKEN=gldt-KzooQLKR9hstfKw-FvxsBs2bzQFJDG0Vy9R", "docker login registry.example.com -u deploy -p gldt-Mbpq99FJ02j5iOP_hnZ4"},
			nomatch: []string{"gldt-tiny1", "gldt-abcDE12345 KzooQLKR9hstfKw-FvxsBs2bzQFJDG0Vy9R", "gldt-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "gitlab-pat",
			match:   []string{"GITLAB_PAT=glpat-BO_yY1vy1Dx71XJWCS_eOE50i2nLmR", "Authorization: Bearer glpat-9M71uUC6dXE67HSyDv5S0ZGci"},
			nomatch: []string{"glpat-abc123", "glpat-abcDE12345 BO_yY1vy1Dx71XJWCS_eOE50i2nLmR", "glpat-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "gitlab-runner-token",
			match:   []string{"CI_RUNNER_TOKEN=glrt-dJc9SE3diMqM_KM3RYy7XNeTwCI_", "{\"token\": \"glrt-EmRFgtLiVRnl7YoMV36D9C\"}"},
			nomatch: []string{"glrt-short1", "glrt-abcDE12345 dJc9SE3diMqM_KM3RYy7XNeTwCI_", "glrt-XXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "groq-api-key",
			match:   []string{"GROQ_API_KEY=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", "Authorization: Bearer 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", "{\"groq_api_key\": \"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\"}"},
			nomatch: []string{"gsk_short", "gsk_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "gsk_wJbCoeH86zjKgop71T4-viLZ6QRKh2kwaIp2lYCV9MiujTbzw3MA", "gsk_wJbCoeH86zjKgop71T4uviLZ6QRKh2kwaIp2lYCV9MiujTbzw3MAZ"},
		},
		{
			id:      "huggingface-token",
			match:   []string{"HUGGINGFACE_TOKEN=hf_nW2OPJ0rGsD6y4OUtEXQxmAa3BItWMoP6J", "Authorization: Bearer hf_SoSitdlyJv4jWuJOgem50hOrLw9OoFOcb4", "{\"token\": \"hf_nW2OPJ0rGsD6y4OUtEXQxmAa3BItWMoP6J\"}"},
			nomatch: []string{"hf_short", "hf_ab-cdefghijklmnopqrstuvwxyz01234", "from transformers import hf_hub_download", "hf_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "linear-api-key",
			match:   []string{"export LINEAR_API_KEY=lin_api_FeWaVUqG2KVasfSq8Z0wjCdFUQUHxZ3g0Aq3idaD", "{\"linear_api_key\": \"lin_api_MhXnwfocwDNRjI7Sc4sfHBomzPtKTjAjaFO16Hd8Hp1Jf7tSgtRa1eePdjJY\"}"},
			nomatch: []string{"lin_api_M6mgv4I3ERxy2aV7ygR0ASuT1llqf3", "lin_api_FeWaVUqG2KVasfSq8Z0wjCdF-UQUHxZ3g0Aq3idaD", "lin_api_QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ"},
		},
		{
			id:      "notion-internal-token",
			match:   []string{"export NOTION_TOKEN=secret_JcieWVjwiYd7U3MsPkYO2xaCUvet6zYYqy0pJf9CIg9", "{\"notion_secret\": \"secret_lV3G32cGh6dAuJa3pJEeyQVnsZpF2V2r2iY9Uot4wf3\"}", "export NOTION_TOKEN=ntn_LFn3YnrPf6lJOdoQdQqA5zd5SriKEc8WlTo9bsQd2TMY2e", "{\"notion_token\": \"ntn_GPYkWkSsSB1qZRAk3rxvD6mvf155SxzOmzWOoMnQrwuxqr1IoG5opCTycClX\"}"},
			nomatch: []string{"the client_secret_JcieWVjwiYd7U3MsPkYO2xaCUvet6zYYqy0pJf9CIg9 field", "token=secret_iCnEPor6SOvFbGwot3GcKsT5BCUyDSWXbJPhakryLK", "token=ntn_uIF6SUvaLMIyi4Xhg6R1KQ608e9zSv3VzHd9EJw9O3rur"},
		},
		{
			id:      "npm-access-token",
			match:   []string{"NPM_TOKEN=npm_plknz1kJAShTH8KvwDZPcixBekByPBAakTBO", "//registry.npmjs.org/:_authToken=npm_TOltgSxsXbtv4bMFG9MvKZHj0LRUG1a6nKiZ"},
			nomatch: []string{"npm_config_registry=https://registry.npmjs.org/", "npm_config_yes=true", "NPM_TOKEN=npm_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "NPM_TOKEN=npm_short"},
		},
		{
			id:      "openai-legacy-key",
			match:   []string{"OPENAI_API_KEY=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", "Authorization: Bearer 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", "{\"key\": \"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\"}"},
			nomatch: []string{"sk-abcdEFGH12", "sk-70Ii88WRAFMcMAhCWPfOagj8Ggq8MY8sbFU24lQSbfFBDwJn", "Authorization: Bearer sk-ant-api03-L6VtNHDzbvOYIs52KThe1DBzYMxIsTnjxqnzKJgS1niDgzJKhy20RHoBqBbuVcPjhcUAwu89LeznSyn2bpa26sQIrfAA", "OPENAI_API_KEY=sk-proj-BVNMKlvU9FzBvWdqOPDZtJVcBIS5TvkvuzSLy8asT3BlbkFJLq83zMskErFlHpuT9KMBRkPgrihZPskJwst1ctDX", "This model carries elevated risk-taking behavior in production."},
		},
		{
			id:      "openai-project-key",
			match:   []string{"OPENAI_API_KEY=sk-proj-BVNMKlvU9FzBvWdqOPDZtJVcBIS5TvkvuzSLy8asT3BlbkFJLq83zMskErFlHpuT9KMBRkPgrihZPskJwst1ctDX", "Authorization: Bearer sk-svcacct-4zROgBOLNt0ZP9sqaEZXj8WJxMSWeuquxqsQX6zBjK1bJpnvzDHlclD7U6Ro", "{\"config\": {\"openai_key\": \"sk-admin-4zROgBOLNt0ZP9sqaEZXj8WJxMSWeuquxqsQX6zBjK1bJpnvzDHlclD7U6Ro\"}}"},
			nomatch: []string{"sk-proj-0JBJkQfgbsuTgzoeHx6jHkf5g1sKJ2", "sk-svcacct-abc$%^&*()", "sk-admin-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "The vendor's risk-proj-ection model still relies on legacy tools."},
		},
		{
			id:      "pem-private-key",
			match:   []string{"-----BEGIN OPENSSH PRIVATE KEY-----\nrpvGMXOAKGX6B+kpekdCsOtzCoV+ZuCNdBcPTT9hA6rOjKjGc6MefdDU8p5oXcY7\nrmqoDH0qVi/huXgpY1qHTa43gddwT5TXFrrNosHPdl19o2Z+/7piAa2GqytsZN3C\n2uCmH6CHd67YEB0uS5MMuWrzaXnJ0gfBwd91bSrUJj9LZRsK1PbRQUyZJjzlxYuw\n75dnx5rqKXyLS8Zhms26Wg==\n-----END OPENSSH PRIVATE KEY-----\n", "-----BEGIN RSA PRIVATE KEY-----\n+d8lz6RCC7suHWdngVelufP37AbgZFNOdJDmYi8VNuz6KOrxYDc15SKUJi+H3/sV\nJNHCUb7b3BpnOGRLa+2yMuias21KPFR8Axm4JzRUdrDSzQz+J0dAs2b7Dic7gm2O\nHwdixVZHihKkCBzhlDoM4CMLCKwn83R/n895ffXcXqy9pHuEd0qu9765175ufW5h\n-----END RSA PRIVATE KEY-----\n", "{\"event\":\"agent_exec\",\"secret\":\"-----BEGIN OPENSSH PRIVATE KEY-----\\nMPjfSFCnwhGTQ+Nb7jYRFRuaHWmQZy/qYe4benpW2R0Ipl3erdPWAsL8ju10Qwgr\\nFBwciFpPb32JqfTqqxEhjtg47xRCoOfQbEJfUzmdn52uzmNOJqnmNKCyiLf9QWsq\\n-----END OPENSSH PRIVATE KEY-----\\n\"}", "-----BEGIN RSA PRIVATE KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: AES-128-CBC,A1B2C3D4E5F60718293A4B5C6D7E8F90\n\ntLQfbEBiLk97Gc+CQPmipyAB7Ve5n/Vw+LWbnt0ao6mWMkOGu4gFlxRMIzmEBqeo\n6jNqZ5NfymdkR6RBmPsCQ9qLSdrpmeeEsJS0XG6On2Vu+B2s17OWsV0yKXc0ubiG\n-----END RSA PRIVATE KEY-----\n", "-----BEGIN PRIVATE KEY-----\npXIKj1muE8wjxUB4P1NbhSPqyP1epR04JEmb6DTk/MjMhfvfk9bIc/z+mHPIuvz/\n2xmt9Ru7t5EBG+JmdLz4/hKQL6tv1KsQb7VSpSIMeFwomJ620IQMBajXgnRC8f0w\nYmicg//E+BFDyb76VongDyy7sllrDOdbcTeMkg5yJvwRQXxIaYNi0BhkMfrL08Lz"},
			nomatch: []string{"-----BEGIN CERTIFICATE-----\nFc6xc4/fGGyOOMLU524WciLQYdWNI1g0r0yU5Zt2vWuLiLGoL4my/oP7adWIj2Rk\n-----END CERTIFICATE-----\n", "-----BEGIN PUBLIC KEY-----\nDgTef9Rdy/5scNY8uQgLKB9qLJNYHnvJ51I7WIcAmgkh28NbBFn9gqwcO8ma5pJ9\n-----END PUBLIC KEY-----\n", "-----BEGIN PRIVATE KEY----- is the PEM header", "-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----\n"},
		},
		{
			id:      "putty-private-key",
			match:   []string{"PuTTY-User-Key-File-2: ssh-rsa\nEncryption: none\nComment: synthetic-fixture\nPublic-Lines: 2\nJNHCUb7b3BpnOGRLa+2yMuias21KPFR8Axm4JzRUdrDSzQz+J0dAs2b7Dic7gm2O\nHwdixVZHihKkCBzhlDoM4CMLCKwn83R/n895ffXcXqy9pHuEd0qu9765175ufW5h\nPrivate-Lines: 2\ntLQfbEBiLk97Gc+CQPmipyAB7Ve5n/Vw+LWbnt0ao6mWMkOGu4gFlxRMIzmEBqeo\n6jNqZ5NfymdkR6RBmPsCQ9qLSdrpmeeEsJS0XG6On2Vu+B2s17OWsV0yKXc0ubiG\nPrivate-MAC: 6f1c2b3a4d5e6f708192a3b4c5d6e7f8091a2b3c\n", "PuTTY-User-Key-File-3: ssh-ed25519\nEncryption: none\nComment: synthetic-truncated\nPublic-Lines: 1\nFc6xc4/fGGyOOMLU524WciLQYdWNI1g0r0yU5Zt2vWuLiLGoL4my/oP7adWIj2Rk\nPrivate-Lines: 6\nrpvGMXOAKGX6B+kpekdCsOtzCoV+ZuCNdBcPTT9hA6rOjKjGc6MefdDU8p5oXcY7\nrmqoDH0qVi/huXgpY1qHTa43gddwT5TXFrrNosHPdl19o2Z+"},
			nomatch: []string{"PuTTY-User-Key-File-9: ssh-rsa\nEncryption: none\nPrivate-Lines: 1\npXIKj1muE8wjxUB4P1NbhSPqyP1epR04JEmb6DTk/MjMhfvfk9bIc/z+mHPIuvz/\n", "PuTTY-User-Key-File-2: ssh-rsa\nEncryption: none\nComment: public-only\nPublic-Lines: 1\nDgTef9Rdy/5scNY8uQgLKB9qLJNYHnvJ51I7WIcAmgkh28NbBFn9gqwcO8ma5pJ9\n", "the PuTTY-User-Key-File-2 format stores Private-Lines: 14 body lines"},
		},
		{
			id:      "pypi-api-token",
			match:   []string{"PYPI_API_TOKEN=pypi-AgEIcHlwaS5vcmciP1aKP8I598r9hDBybMnEIx9dj0L-mNSWyd04f1Ibz0rFbGOnIRyMex-3LajVwjAeU-5aeC_7TS", "twine upload --repository pypi --password pypi-Kx3nk2FwGJA8cZG3hRAq7b_1nfEB9W8xiavowuP8SWVADE1tXNac50deIoGvPKXvSt3lTrHxfFid0utBAisqoF_I6b6SFx4fDBmH dist/*"},
			nomatch: []string{"pypi-tooShortToken1234567890", "pypi-abcDE12345 Fy7lOBCGPVunOMqKKLByo2Azdma5XY3XWladYTLBrX1P9HS2JJWJTgPCEQQLtkaREmFr1hs7k7dnztUQC9AsSxYc1x", "pypi-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "sendgrid-api-key",
			match:   []string{"curl -H \"Authorization: Bearer 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\" https://api.sendgrid.com/v3/mail/send", "SENDGRID_API_KEY=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"},
			nomatch: []string{"SG.ci3_DxrzV7QDyDK2R7XGh.wpb6prwj1gK8CGscIFDfZCTeQ8Ob7gvVOUnNDnwyZJf", "SG.OhWhEN3so3OxYgF3AZu3Iq.oPmn0pzlQY1wWmzAmka p744b8VKkqLencZSDFf8J61", "the MSG.OhWhEN3so3OxYgF3AZu3Iq.oPmn0pzlQY1wWmzAmka3p744b8VKkqLencZSDFf8J61 was logged"},
		},
		{
			id:      "slack-app-token",
			match:   []string{"export SLACK_APP_TOKEN=xapp-1-GPMM82I1LR3-3178108013267-f6c15c0c8e9df469611a11f5125227c3712da86a78c49ea20e32684b27b95e90", "{\"app_token\": \"xapp-2-9TGIQHG9JR-4935348740-2d810a485ed03241b4d419b1b673bd4755d05ad7853c1f76eb97706ca828bca0\"}"},
			nomatch: []string{"xapp-1-ABC-123", "xapp-AAAAAAAAAAAAAAAAAAAA-BBBBBBBBBBBBBBBBBBBBBB", "xapp------------------------------------------"},
		},
		{
			id:      "slack-bot-token",
			match:   []string{"xoxb-0265423511615-5940781618495-KmTecQoXsf2o3gyrDO1xkxwnQrS7RP"},
			nomatch: []string{"xoxb-123-456-abcdefgh", "xoxb-0265423511615-5940781618495-aaaaaaaaaaaaaaaaaaaaaaaaaaaa", "xoxb-99603082462819-48219935181-KdNnFRIBXuDL7DxtpYlSXpfKtHF4"},
		},
		{
			id:      "slack-user-token",
			match:   []string{"export SLACK_USER_TOKEN=xoxa-80184514627-048281489325-wKi9x7h6AmUfBH7X41zTPDP4k8FFuf", "{\"token\": \"xoxp-1822782489-63834657871-331509839301-1721a278f64f7fd633dbdde1\"}"},
			nomatch: []string{"xoxa-123-456-abcdefgh0123456789abcd", "xoxa-80184514627-048281489325-rppGDZuVz3", "xoxa-80184514627-048281489325-aaaaaaaaaaaaaaaaaaaaaaaaaaaa"},
		},
		{
			id:      "stripe-secret-key",
			match:   []string{"curl https://api.stripe.com/v1/charges -u sk_live_oHBvRPOIvGrv5iFlbCBFNOgmBjMtpsia:", "STRIPE_SECRET_KEY=sk_test_OclRz3AwzKsbVRJN9wVGFYGW"},
			nomatch: []string{"sk_live_2WmQzCudiH", "sk_live_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "sk_live_oHBvRPOIvGrv5iFlbCBF-NOgmBjMtpsia"},
		},
		{
			id:      "stripe-webhook-secret",
			match:   []string{"STRIPE_WEBHOOK_SECRET=whsec_7YFjS1on43XkMtECqOxSF2O3GYRdo1XKXWNqRs7r", "{\"stripe_webhook_secret\": \"whsec_pEmoKiuPKdYR7osjOrU1xxDO0CzUZREN68k4tUNpfZ46pdJQIPvjiQvlb5lZXOIg\"}"},
			nomatch: []string{"whsec_fFwD3HJoKyrbmEYYmdhQ", "whsec_ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "whsec_7YFjS1on43XkMtECqOx_SF2O3GYRdo1XKXWNqRs7r"},
		},
		{
			id:      "twilio-api-key-sid",
			match:   []string{"export TWILIO_API_KEY_SID=SK3931bdb2a0df3dbe4d58fed8a728e7ec", "{\"api_key_sid\": \"SKa0fa5f6b8a880627df7ffe0297c79bfb\"}"},
			nomatch: []string{"SKDABE898736A3566F893697B590481194", "SKf309ffea518f32cf21449273d7cee9", "the TASKd9136682575250def91799e2786d3748 list", "clean the DESK421599e3e9c8fe21da80270815fe85df now"},
		},
		{
			id:      "url-credentials",
			match:   []string{"DATABASE_URL=postgres://svc_user:wZ8kQ3vR7pL4mN2x@db.internal:5432/app", "redis://:q8LmPz31vTk@cache.prod.svc:6379/0", "{\"msg\":\"connecting\",\"dsn\":\"mysql://root:Vt5xK8nQ2wZ7@10.0.0.12:3306/orders\"}", "amqps://ingest:R7pL4mN2xT6b@mq.internal:5671/%2Fprod"},
			nomatch: []string{"https://deploy@github.com/org/repo.git", "postgres://user:password@localhost:5432/db", "see http://user:pass@host.example.com for the URL shape", "redis://:@cache.internal:6379", "note: the \"://\" separator splits scheme from authority", "https://status.example.com/healthz"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.id, func(t *testing.T) {
			rule, ok := generatedFixtureRule(tc.id)
			if !ok {
				t.Fatalf("rule %q not registered in Builtins()", tc.id)
			}
			for _, fx := range tc.match {
				if !generatedFixtureConfirms(rule, fx) {
					t.Errorf("rule %q: match fixture %q: want a trigger occurrence to validate, none did", tc.id, fx)
				}
			}
			for _, fx := range tc.nomatch {
				if generatedFixtureConfirms(rule, fx) {
					t.Errorf("rule %q: nomatch fixture %q: want no trigger occurrence to validate, one did", tc.id, fx)
				}
			}
		})
	}
}

// generatedFixtureRule, generatedFixtureConfirms, and their helpers below
// are static: their code does not depend on the specs, only on the
// (id, match, nomatch) table above, so they are byte-identical across
// regenerations that don't change the rulegen version.

func generatedFixtureRule(id string) (Rule, bool) {
	for _, r := range Builtins() {
		if r.ID == id {
			return r, true
		}
	}
	return Rule{}, false
}

// generatedFixtureConfirms reports whether at least one occurrence of one
// of rule's triggers within data is confirmed by rule.Validate, using the
// window rule.MaxLookbehind/MaxLookahead would produce at that offset
// (clamped to data's bounds).
func generatedFixtureConfirms(rule Rule, data string) bool {
	b := []byte(data)
	for _, trig := range rule.Triggers {
		for _, occ := range generatedFindOccurrences(b, trig) {
			lo := occ.start - rule.MaxLookbehind
			if lo < 0 {
				lo = 0
			}
			hi := occ.end + rule.MaxLookahead
			if hi > len(b) {
				hi = len(b)
			}
			window := b[lo:hi]
			ts, te := occ.start-lo, occ.end-lo
			if _, _, ok := rule.Validate(window, ts, te); ok {
				return true
			}
		}
	}
	return false
}

type generatedOccurrence struct{ start, end int }

// generatedFindOccurrences returns every occurrence (including overlapping
// ones) of trig.Literal in data, honoring trig.CaseFold with the ASCII
// case folding rule from docs/DESIGN.md (fold 'A'-'Z' to lowercase on both
// sides).
func generatedFindOccurrences(data []byte, trig Trigger) []generatedOccurrence {
	lit := []byte(trig.Literal)
	if len(lit) == 0 || len(lit) > len(data) {
		return nil
	}
	var out []generatedOccurrence
	for i := 0; i+len(lit) <= len(data); i++ {
		if generatedASCIIEqualFold(data[i:i+len(lit)], lit, trig.CaseFold) {
			out = append(out, generatedOccurrence{start: i, end: i + len(lit)})
		}
	}
	return out
}

func generatedASCIIEqualFold(a, b []byte, caseFold bool) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		ac, bc := a[i], b[i]
		if caseFold {
			ac = generatedASCIIFoldByte(ac)
			bc = generatedASCIIFoldByte(bc)
		}
		if ac != bc {
			return false
		}
	}
	return true
}

func generatedASCIIFoldByte(c byte) byte {
	if c >= 'A' && c <= 'Z' {
		return c - 'A' + 'a'
	}
	return c
}
