// Code generated by rulegen from internal/rules/specs. DO NOT EDIT.
//
// Provenance:
//   anthropic-api-key: https://docs.anthropic.com/en/api/getting-started (original)
//   authorization-bearer: https://www.rfc-editor.org/rfc/rfc6750 (Bearer); https://www.rfc-editor.org/rfc/rfc7617 (Basic); https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html (AWS SigV4) (original)
//   aws-access-key-id: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-unique-ids (original)
//   aws-bedrock-long-lived-api-key: https://docs.aws.amazon.com/bedrock/latest/userguide/api-keys.html; https://github.com/awslabs/git-secrets (original)
//   aws-bedrock-short-lived-api-key: https://docs.aws.amazon.com/bedrock/latest/userguide/api-keys.html; https://github.com/aws/aws-bedrock-token-generator-js; https://github.com/awslabs/git-secrets (original)
//   aws-secret-access-key: https://docs.aws.amazon.com/general/latest/gr/aws-access-keys-best-practices.html (original)
//   azure-app-configuration-secret: https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core-push-refresh; https://learn.microsoft.com/en-us/azure/service-connector/how-to-integrate-app-configuration (original)
//   azure-servicebus-sas-key: https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas; https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-get-connection-string (original)
//   azure-storage-account-key: https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage (original)
//   buildkite-api-token: https://buildkite.com/docs/apis/managing-api-tokens; https://buildkite.com/docs/agent/v3/tokens (original)
//   cerebras-api-key: Third-party integration guides converging on csk-<32-char alphanumeric> (e.g. csk-1234567890abcdef1234567890abcdef); Cerebras's own docs (inference-docs.cerebras.ai) were unreachable during development and no gitleaks/TruffleHog rule exists to cross-check against — should be re-verified against Cerebras's own docs when reachable (original)
//   circleci-token: https://circleci.com/changelog/new-format-for-api-access-tokens; https://circleci.com/docs/managing-api-tokens/ (original)
//   cohere-api-key: gitleaks cohere-api-token rule (github.com/gitleaks/gitleaks config/gitleaks.toml): keyword CO_API_KEY/cohere + 40-char alphanumeric, no fixed prefix on the key itself (original)
//   command-line-password-flag: Original project design; no single external specification (original)
//   cookie-session-token: https://www.rfc-editor.org/rfc/rfc6265 (original)
//   cursor-api-key: Cursor's own sensitive-prompt-guard hook script (github.com/cursor/cookbook hooks/.cursor/hooks/sensitive-prompt-guard.sh): crsr_[A-Za-z0-9_-]{20,}, an open floor with no upper bound (original)
//   datadog-api-key: https://docs.datadoghq.com/agent/guide/environment-variables/ (original)
//   datadog-application-key: https://registry.terraform.io/providers/DataDog/datadog/latest/docs (original)
//   deepgram-api-key: TruffleHog deepgram detector (github.com/trufflesecurity/trufflehog pkg/detectors/deepgram/deepgram.go): 40-char lowercase alphanumeric, no fixed prefix on the key itself (original)
//   deepseek-api-key: TruffleHog deepseek detector (github.com/trufflesecurity/trufflehog pkg/detectors/deepseek/deepseek.go): sk- + 32 lowercase alphanumeric (original)
//   dockerhub-oat: Docker's own docs describe organization access tokens as a distinct type (docs.docker.com/security/access-tokens/) but don't publish a byte-level format; prefix and 32-char floor cross-checked between TruffleHog (pkg/detectors/dockerhub/v2/dockerhub.go) and the betterleaks gitleaks fork (config/betterleaks.toml) (original)
//   dockerhub-pat: https://docs.docker.com/security/for-developers/access-tokens/ (original)
//   doppler-token: https://docs.doppler.com/reference/auth-token-formats (original)
//   gcp-api-key: https://cloud.google.com/docs/authentication/api-keys (original)
//   generic-api-key-assignment: Original project design: assignment-style generic credential heuristic; no single external specification (original)
//   generic-bearer-like-token-assignment: Original project design: assignment-style generic credential heuristic; no single external specification (original)
//   generic-password-assignment: Original project design: assignment-style generic credential heuristic; no single external specification (original)
//   generic-secret-assignment: gitleaks/betterleaks generic-api-key rule (github.com/gitleaks/gitleaks, github.com/betterleaks/betterleaks config/*.toml): both require one of a broad keyword set (access, auth, api, credential, creds, key, password, secret, token) followed within ~20 characters by an assignment operator -- confirmed neither rule is actually keyword-free despite sometimes being described that way (original)
//   github-app-token: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats (original)
//   github-fine-grained-pat: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats (original)
//   github-oauth-token: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats (original)
//   github-pat: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats (original)
//   github-refresh-token: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats (original)
//   gitlab-deploy-token: https://docs.gitlab.com/user/project/deploy_tokens/ (original)
//   gitlab-feed-token: https://docs.gitlab.com/security/tokens/#token-prefixes; gitleaks gitlab-feed-token rule; GitLab's own app/models/user.rb FEED_TOKEN_PREFIX and client-side secret_detection_patterns.js (original)
//   gitlab-feed-token-v2: GitLab's own lib/gitlab/auth/auth_finders.rb path_dependent_feed_token_regex: /\A(glft-)(\h{64})-(\d+)\z/ — an HMAC-SHA256 digest of the feed path keyed by the user's real feed token, plus a dash-separated numeric user ID (original)
//   gitlab-pat: https://docs.gitlab.com/user/profile/personal_access_tokens/#create-a-personal-access-token (original)
//   gitlab-pipeline-trigger-token: https://docs.gitlab.com/security/tokens/#token-prefixes; GitLab's own client-side app/assets/javascripts/lib/utils/secret_detection_patterns.js (40-char [0-9a-zA-Z_-] body), cross-checked against gitleaks' gitlab-ptt rule (40-char length agrees, narrower hex-only alphabet) (original)
//   gitlab-runner-token: https://docs.gitlab.com/ci/runners/new_creation_workflow/#glrt-authentication-tokens (original)
//   grafana-cloud-access-policy-token: https://grafana.com/blog/2022/11/22/meet-grafana-cloud-access-policies-the-new-cloud-api-keys/ (original)
//   grafana-service-account-token: https://grafana.com/docs/grafana/latest/administration/service-accounts/ (original)
//   groq-api-key: https://console.groq.com/docs/quickstart (original)
//   huggingface-token: https://huggingface.co/docs/hub/security-tokens (original)
//   jwt: https://www.rfc-editor.org/rfc/rfc7519 (JWT); https://www.rfc-editor.org/rfc/rfc7515#section-3.1 (JWS compact serialization); shape modeled on the betterleaks standalone-JWT rule (original)
//   linear-api-key: https://developers.linear.app/docs/graphql/working-with-the-graphql-api#personal-api-keys (original)
//   notion-internal-token: https://developers.notion.com/docs/authorization (original)
//   npm-access-token: https://docs.npmjs.com/about-access-tokens (original)
//   openai-legacy-key: https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety (original)
//   openai-project-key: https://help.openai.com/en/articles/9186755-managing-your-work-in-the-api-platform-with-projects (original)
//   pem-private-key: https://datatracker.ietf.org/doc/html/rfc7468 (original)
//   putty-private-key: https://tartarus.org/~simon/putty-snapshots/htmldoc/AppendixC.html (original)
//   pypi-api-token: https://docs.pypi.org/api/secrets/ (original)
//   sendgrid-api-key: https://docs.sendgrid.com/ui/account-and-settings/api-keys (original)
//   slack-app-token: https://api.slack.com/authentication/token-types#app-level (original)
//   slack-bot-token: https://api.slack.com/authentication/token-types#bot (original)
//   slack-user-token: https://api.slack.com/authentication/token-types#user (original)
//   stripe-ephemeral-key: Real (structure-only) fixtures in Stripe's own stripe-ios (github.com/stripe/stripe-ios) and stripe-android SDK repositories; docs.stripe.com/keys was unreachable during development and neither gitleaks nor TruffleHog has a rule for this key type (original)
//   stripe-secret-key: https://docs.stripe.com/keys (original)
//   stripe-webhook-secret: https://docs.stripe.com/webhooks#verify-official-libraries (original)
//   supabase-service-role-key: https://supabase.com/docs/guides/api/api-keys (legacy JWT-based service_role key, distinguished from the anon key by its "role":"service_role" claim, which Postgres row-level-security policies treat as bypassing RLS); https://www.rfc-editor.org/rfc/rfc7519 (JWT claims) (original)
//   terraform-cloud-api-token: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/user-tokens; https://developer.hashicorp.com/terraform/cloud-docs/api-docs/team-tokens; https://developer.hashicorp.com/terraform/cloud-docs/api-docs/organization-tokens (original)
//   twilio-api-key-sid: https://www.twilio.com/docs/iam/api-keys (original)
//   url-credentials: https://www.rfc-editor.org/rfc/rfc3986#section-3.2.1 (original)
//   vault-batch-token: https://github.com/hashicorp/vault/blob/main/vault/token_store.go; https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml (original)
//   vault-service-token: https://github.com/hashicorp/vault/blob/main/vault/token_store.go; https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml (original)
//   vercel-legacy-token: https://vercel.com/docs/cli; https://vercel.com/docs/rest-api (original)
//   vercel-token: https://vercel.com/changelog/new-token-formats-and-secret-scanning (original)

package rules

import "testing"

// TestGeneratedRuleFixtures confirms that every match fixture in
// internal/rules/specs is confirmed by its rule's Validate at some trigger
// occurrence, and that every nomatch fixture is confirmed at none.
func TestGeneratedRuleFixtures(t *testing.T) {
	cases := []struct {
		id      string
		match   []string
		nomatch []string
	}{
		{
			id:      "anthropic-api-key",
			match:   []string{"Authorization: Bearer sk-ant-api03-L6VtNHDzbvOYIs52KThe1DBzYMxIsTnjxqnzKJgS1niDgzJKhy20RHoBqBbuVcPjhcUAwu89LeznSyn2bpa26sQIrfAA", "ANTHROPIC_API_KEY=sk-ant-admin01-V9AoHGzkZ5UL5o2kDCaFfewEFjXIn7vunFmrPxZZ28kDnJnDY4XLZ6XJmYO2aYzQMmLdhMAA83LqYzEQa8qbJ", "{\"config\": {\"anthropic_api_key\": \"sk-ant-api03-L6VtNHDzbvOYIs52KThe1DBzYMxIsTnjxqnzKJgS1niDgzJKhy20RHoBqBbuVcPjhcUAwu89LeznSyn2bpa26sQIrfAA\"}}"},
			nomatch: []string{"sk-ant-api03-short", "ANTHROPIC_API_KEY=sk-ant-xxxxxxxx…", "sk-ant-api03-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "The zoo increased its risk-ant-eater enclosure budget this year.", "ANTHROPIC_API_KEY=sk-ant-api03-jQrK7vN2mPxY8zT5aB6cD9eF1gH4iJ"},
		},
		{
			id:      "authorization-bearer",
			match:   []string{"GET /v1/orders HTTP/1.1\nHost: api.example.com\nAuthorization: Bearer kJ8vQ2mZ7xW4pL9sN3tYbF6hR0cD5gU1aE\nAccept: */*\n", "curl -H 'Proxy-Authorization: Bearer nQ7wL4mX8pZ1sT6bK3jH0cV5yR2dF9gA' https://api.example.com/v1", "{\"event\":\"http\",\"line\":\"\\\"authorization: bearer eyJhbGciOiJIUzI1NiJ9.pZ8kQ2vR7wL4mN0pX1sT.hB3jF6hZ1cYdA0eBqG\\\"\"}", "Authorization: Basic c3ZjLXVzZXI6a0o4dlEybVo3eFc0cEw5cw==", "Authorization: AWS4-HMAC-SHA256 Credential=AKIAUJZDEGXDNCF32EPF/20260810/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=7f3a92c1e8b4d06f5a2c9e17b3d84f60a1c5e29b7d4f18a3c6e05b92d7f41a8c"},
			nomatch: []string{"Authorization: Bearer <token>", "Authorization: Bearer ${API_TOKEN}", "# example: Authorization: Bearer YOUR-TOKEN-HERE-1234", "Authorization: Basic dXNlcjE=", "Authorization: Digest username=\"user1\", realm=\"api\", nonce=\"dcd98b7102dd2f0e\", response=\"6629fae49393a05397450978507c4ef1\"", "authorization: bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "Authorization: Bearer USER_ACCESS_TOKEN"},
		},
		{
			id:      "aws-access-key-id",
			match:   []string{"AWS_ACCESS_KEY_ID=AKIAUJZDEGXDNCF32EPF", "{\"accessKeyId\": \"ASIA3DHODZDOCIS2JHTL\", \"region\": \"us-east-1\"}", "aws configure set aws_access_key_id ACCAGMXGEDN73U55XTPL"},
			nomatch: []string{"AWS_ACCESS_KEY_ID=AKIASHORT", "AWS_ACCESS_KEY_ID=AKIAujzdegxdncf32epf", "AWS_ACCESS_KEY_ID=XAKIAUJZDEGXDNCF32EPF", "AWS_ACCESS_KEY_ID=AKIAUJZDEGXDNCF32EPF9", "# example from the AWS docs: AKIAIOSFODNN7EXAMPLE"},
		},
		{
			id:      "aws-bedrock-long-lived-api-key",
			match:   []string{"AWS_BEARER_TOKEN_BEDROCK=ABSKQmVkcm9ja0FQSUtleS1JsxxGJaQ4E7VYU861k0Q2JFWurEFcHTB3pWIQsxSkp17IPEFuZJ3LArOxD1u7fB08el5jzT3r5+5VZtUxmlfUSk2VaOi1tSZz3ARZsPFTH+BW", "Authorization: Bearer ABSKQmVkcm9ja0FQSUtleSlRvuuRnt7Y3o6/Q75w8HPaglhAJxUx5Ayt9W+dXYUTiNW8XCYbXU1vvUoIQYUm1lHGdHQyywBI6VetDUAP8gleQJlIpJZ4J97nrpRrXps+PhB2tMROOlsn5She1qBi4hWthgd5CeARuVfb12mwEQ54=="},
			nomatch: []string{"ABSKQmVkcm9ja0FQSUtleS0ITXcfEizf9p/ipTSw4dhRz68i9+ZVFYXE+s3GQoCTnVmfRUtn"},
		},
		{
			id:      "aws-bedrock-short-lived-api-key",
			match:   []string{"AWS_BEARER_TOKEN_BEDROCK=bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29tOvUPuU/PvaMhbol1ZyMjdn5udwoLB7xX0cr33qbGURHJUg4hNRSbHRfK5a4C4NSIS+kyy+mZA8aGG7QIU8GfPEHvflcBc6GAs2jGhA6dy1RV1of2wVtCK8ezu5mAdYTn1V8wdoZBsiZrGINe9lh7kFlpI0NYPew35N2Jlf4RM+0fzFJDMiSTu+IgWQ512K7kkHF7xjgYmJFpEJvmGW5+08pbKK2Xas4qyOSCPmsO6lGxxrMp7i98XG4IqFPkc+rt9bFUnW9uoJT6Sy4SnHeY6zpTkU18MxorrBZperajgvaN", "Authorization: Bearer bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29tKSpybDxEDr1zJkNrNg0CfS39lWZIUzBRDmsQTTGcCDO4DudsHfptBHDXTCjN=="},
			nomatch: []string{"bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29t35bxEdKAy+"},
		},
		{
			id:      "aws-secret-access-key",
			match:   []string{"AWS_SECRET_ACCESS_KEY=fKm/r5kJP1VrT+1FJors/6ILi8IHn5kxsC7tVO/H", "aws_secret_access_key: bkQfyy/KV5zjR3j1twdTKWTddB+XhkAS1voQG6yy", "aws_secret_access_key = 'fKm/r5kJP1VrT+1FJors/6ILi8IHn5kxsC7tVO/H'", "{\"aws_secret_access_key\": \"fKm/r5kJP1VrT+1FJors/6ILi8IHn5kxsC7tVO/H\"}"},
			nomatch: []string{"AWS_SECRET_ACCESS_KEY=tooshort", "AWS_SECRET_ACCESS_KEY aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "AWS_SECRET_ACCESS_KEY=fKm/r5kJP1VrT+1FJors/6ILi8IHn5kxsC7tVO/!", "aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"},
		},
		{
			id:      "azure-app-configuration-secret",
			match:   []string{"AZURE_APPCONFIG_CONNECTION_STRING=Endpoint=https://contoso.azconfig.io;Id=abcd-e6-s0:tl6ABcdefGHi7kLMno;Secret=mmxAIeZe895Wtq/pyHd+4RKKU6RfN71uJyIJ1Vzm53g=", "{\"connectionString\":\"Endpoint=https://contoso.azconfig.io;Id=09pv-l0-s0:opFCQMC6zZ9485xJgN;Secret=iaTWpoAYKKGb273wx7ErgccAESuzBn3NcoaAoP37zKP=\"}"},
			nomatch: []string{"Secret=jCIM7QEMhof8hn9tGqXB=", "Secret=mmxAIeZe895Wtq/pyHd+4RKKU6RfN71uJyIJ1Vzm53g", "client_secret=mmxAIeZe895Wtq/pyHd+4RKKU6RfN71uJyIJ1Vzm53gXX"},
		},
		{
			id:      "azure-servicebus-sas-key",
			match:   []string{"Endpoint=sb://contoso-ns.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=dLIcySo/hlQZbpcUeroBfki2yLt1qc6PCYFQP79YcXe=", "EVENTHUB_CONNECTION=\"Endpoint=sb://contoso-eh.servicebus.windows.net/;SharedAccessKeyName=send;SharedAccessKey=DLgtjFOrVEiHuAPOAJFIuaiduxuRQ4I/QWODAAReCfD=;EntityPath=orders\""},
			nomatch: []string{"SharedAccessKey=LkkRnssrJa6yw4IUk6yEu4d+yIVGY+=", "SharedAccessKey=dLIcySo/hlQZbpcUeroBfki2yLt1qc6PCYFQP79YcXe", "SharedAccessKey=dLIcySo/hlQZbpcUeroBfki2yLt1qc6PCYFQP79YcXe=="},
		},
		{
			id:      "azure-storage-account-key",
			match:   []string{"DefaultEndpointsProtocol=https;AccountName=contosostorage;AccountKey=5suKcNd8Zra9A9sKPxZ9W3qLy7zKUVQDT7S8sTQCBNR3YbDgbleph1QHt61QTC4XATWS8PHp9NHfYjFM5DI4pZ==;EndpointSuffix=core.windows.net", "AZURE_STORAGE_ACCOUNT_KEY=\"AccountKey=j59fhZ5R1Py4oJe2JbmPTuSgR7cMy+UcU3zr1ZtoLuCr64CxqlIOdNKhiFXiQ2hzT/pLjHX2JiCLhKcIhP6Br1==\""},
			nomatch: []string{"AccountKey=tooshort==", "AccountKey=5suKcNd8Zra9A9sKPxZ9W3qLy7zKUVQDT7S8sTQCBNR3YbDgbleph1QHt61QTC4XATWS8PHp9NHfYjFM5DI4pZ", "AccountKey=5suKcNd8Zra9A9sKPxZ9W3qLy7zKUVQDT7S8sTQCBNR3YbDgbleph1QHt61QTC4XATWS8PHp9NHfYjFM5DI4pZ!!", "AccountKey=5suKcNd8Zra9A9sKPxZ9W3qLy7zKUVQDT7S8sTQCBNR3YbDgbleph1QHt61QTC4XATWS8PHp9NHfYjFM5DI4pZ===extra", "AccountKey=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="},
		},
		{
			id:      "buildkite-api-token",
			match:   []string{"export BUILDKITE_API_TOKEN=7c21bb00e72ed1eabed3610688adf0d449584ebb", "BUILDKITE_AGENT_TOKEN: \"4a8775d65f4bc1cfbea8d77320d26eb307677293\"", "{\"buildkite_api_token\": \"7c21bb00e72ed1eabed3610688adf0d449584ebb\"}"},
			nomatch: []string{"BUILDKITE_API_TOKEN=tooshort", "BUILDKITE_API_TOKEN 7c21bb00e72ed1eabed3610688adf0d449584ebb", "BUILDKITE_API_TOKEN=7C21BB00E72ED1EABED3610688ADF0D449584EBB"},
		},
		{
			id:      "cerebras-api-key",
			match:   []string{"export CEREBRAS_API_KEY=csk-FEy2DbVMMDMkVXPC6VwvroPDghvBVwkk", "Authorization: Bearer csk-JmXBkabEZpEaezCD7X1U3PtUiaNxe7DCOVWmx2W2mEkAWvyYJYMcGyTsXXTRfxVT"},
			nomatch: []string{"csk-short", "csk-WfAcMgPulX4WlCSUGQTSGTipfgoGNm1"},
		},
		{
			id:      "circleci-token",
			match:   []string{"export CIRCLE_TOKEN=CCIPAT_t9WBafchSkTiQvrq4rafRp_4b90c0376d730396770ad17e54c7d6c7d059a2db", "{\"projectApiToken\":\"CCIPRJ_5aCa6zBzxoFWqcJGuwQE_7688c0760c387df4dd4523f92bef162d67f61a43\"}"},
			nomatch: []string{"CCIPAT_short_4b90c0376d730396770ad17e54c7d6c7d059a2db", "CCIPAT_t9WBafchSkTiQvrq4rafRp_4b90c0376d730396770ad17e54c7d6c7d059a2", "CCIPAT_t9WBafchSkTiQvrq4rafRp-4b90c0376d730396770ad17e54c7d6c7d059a2db"},
		},
		{
			id:      "cohere-api-key",
			match:   []string{"export CO_API_KEY=H2KCBhpcOPYhC8jhRqcRSBueRVzkLJKUT5YsB16V", "COHERE_API_KEY: \"ILZo8C46vo3Ipa56xQ9vaey2pW44QkrEmSX61qMH\"", "{\"cohere_api_key\": \"H2KCBhpcOPYhC8jhRqcRSBueRVzkLJKUT5YsB16V\"}"},
			nomatch: []string{"CO_API_KEY=tooshort", "CO_API_KEY=H2KCBhpcOPYhC8jhRqcRSBueRVzkLJKUT5YsB16"},
		},
		{
			id:      "command-line-password-flag",
			match:   []string{"mysql -h db.prod.internal -u app --password=tR8kW3nQ7zXm2 app_db", "vault login --token=hvs.9kQ3vR7wL4mN2xT6bF0jH5cD", "deploy --api-key 'Zp8kQ3vR7wL4mN2xT6bF9jH0' --env prod", "{\"cmd\":\"pg_restore --passwd=Xq7Lm2Vt9zR4 -d app\"}"},
			nomatch: []string{"pg_dump --password-file /run/secrets/pgpass -h db", "fetch --token-url https://auth.example.com/oauth/token", "mysql --password= --host db.internal", "run.sh --password ${DB_PASSWORD}", "docs: use --api-key <your-key> to authenticate", "login --secret changeme --user svc", "deploy --token ${CLOUDFLARE_TUNNEL_TOKEN:?Set token}", "mysql -u root --password=hunter2 mydb"},
		},
		{
			id:      "cookie-session-token",
			match:   []string{"Cookie: theme=dark; sessionid=aK9mQ2vR7wL4mN8pX1sTbF3j; lang=en", "Set-Cookie: sid=xT4bK9mQ2vR7wL0pZ8sN3jH6cY1dF5gA; Path=/; HttpOnly; Secure", "{\"headers\":{\"cookie\":\"gw_route=blue; auth_token=Zp8kQ3vR7wL4mN2xT6bF9jH0cD5yU1aE; region=eu\"}}", "{\"line\":\"\\\"cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.t8ZkQ2vRwLmN4xB7\\\"\"}"},
			nomatch: []string{"Cookie: theme=dark; lang=en; tz=UTC", "Cookie: sessionid=short1; theme=dark", "Set-Cookie: csrftoken=Qw8kV3nR7wL4mN2xT6bF9jH0cD5yU1aE; Path=/", "GET /cb?next=%2Fdash&token=aK9mQ2vR7wL4mN8pX1sTbF3j HTTP/1.1", "Cookie: session=<session-token>; theme=dark", "Cookie: auth=xxxxxxxxxxxxxxxxxxxx; theme=dark", "Cookie: session=1e084479-84e5-4834-bc8a-fc44c29aaed90ffb05&amp; theme=dark"},
		},
		{
			id:      "cursor-api-key",
			match:   []string{"export CURSOR_API_KEY=crsr_3UsvtDPkMeJCkV5Asrqi", "Authorization: Bearer crsr_zmTUVm3EWjXW3eL7NHSMwEicBfcw3IVbjUF3d2kF8PPpH8DncrGeo3AN6UNG", "export CURSOR_API_KEY=crsr_6UOfxC8_G330b9Gv_18TIVt0QP2IYsgln3aeqjn6T80N1CDNB4N_cvyp_OIZNcH8orqZeRes1QWv2CzOTxXHC6wNJUCdi6llz5i_O7edv12CY36k3joG_IIxtf7BBG3ep8mbzArQ4F-KENBllnucuTRmPL-byHAnYHrfPb3weLqpGSJiX-LdSBLSDa3aUEeFFsjb7khz"},
			nomatch: []string{"crsr_short", "crsr_FwfRZvDDlQZYXwcXAD7"},
		},
		{
			id:      "datadog-api-key",
			match:   []string{"DD_API_KEY=af7c06c09c36c278cc2b6013ddcdb1fa datadog-agent start", "dd_api_key: af7c06c09c36c278cc2b6013ddcdb1fa", "{\"dd_api_key\": \"af7c06c09c36c278cc2b6013ddcdb1fa\"}", "DD_API_KEY:\taf7c06c09c36c278cc2b6013ddcdb1fa"},
			nomatch: []string{"DD_API_KEY=tooshort", "dd_api_key=af7c06c09c36c278cc2b6013ddcdb1f", "DD_API_KEY=AF7C06C09C36C278CC2B6013DDCDB1FA"},
		},
		{
			id:      "datadog-application-key",
			match:   []string{"export DD_APP_KEY=9498dbc811f8185ac2b5b7d83d991de5bb18e68e", "dd_app_key: '9498dbc811f8185ac2b5b7d83d991de5bb18e68e'", "{\"dd_app_key\": \"9498dbc811f8185ac2b5b7d83d991de5bb18e68e\"}"},
			nomatch: []string{"DD_APP_KEY=tooshort", "DD_APP_KEY=9498dbc811f8185ac2b5b7d83d991de5bb18e68"},
		},
		{
			id:      "deepgram-api-key",
			match:   []string{"export DEEPGRAM_API_KEY=08f7t2w36t9v3syfilru1v727m8rh2w5me4p0und", "deepgram_api_key: '2x7c1ir87vpi062xqtlsr2t5x9i3qsh8nwo6x3cw'", "{\"deepgram_api_key\": \"08f7t2w36t9v3syfilru1v727m8rh2w5me4p0und\"}"},
			nomatch: []string{"DEEPGRAM_API_KEY=tooshort", "DEEPGRAM_API_KEY=08F7T2W36T9V3SYFILRU1V727M8RH2W5ME4P0UND"},
		},
		{
			id:      "deepseek-api-key",
			match:   []string{"DEEPSEEK_API_KEY=sk-duu8wkernulhwb7g0ncfo1otofxycuyg", "Authorization: Bearer sk-opslnxacaxmopm5g70kfg61k6oa3rnx7"},
			nomatch: []string{"sk-short", "sk-duu8wkernulhwb7g0ncfo1otofxycuy", "sk-DUU8WKERNULHWB7G0NCFO1OTOFXYCUYG", "Authorization: Bearer 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"},
		},
		{
			id:      "dockerhub-oat",
			match:   []string{"DOCKERHUB_OAT=dckr_oat_pEjGcIcQhKLjCKybHVg0UZQ8DSlrD_Km", "{\"password\": \"dckr_oat_x-FB4sKtVkyI8MlQjxZwJgbYVdkwrRA1\"}"},
			nomatch: []string{"dckr_oat_short1234567890123", "dckr_oat_abcDE12345678901 pEjGcIcQhKLjCKybHVg0UZQ8DSlrD_Km", "dckr_oat_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "dockerhub-pat",
			match:   []string{"DOCKERHUB_PAT=dckr_pat_lBYwwQKx2h3qd82R5DtSx3oPE2-xPo0csQ6U", "{\"password\": \"dckr_pat_BMjUC6unM5EYWsQJ8jXp5k_KVfOY\"}"},
			nomatch: []string{"dckr_pat_short12345", "dckr_pat_abcDE12345 lBYwwQKx2h3qd82R5DtSx3oPE2-xPo0csQ6U", "dckr_pat_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "doppler-token",
			match:   []string{"export DOPPLER_TOKEN=dp.st.dev.E96V5JPpZYKbCzr5H2CPYIxrTrz1Td8XAwES2HY0Bk", "DOPPLER_TOKEN=dp.pt.aqlb6WIuPUYGz300dACjXFomKnJmIyOsiN0sJgctY0Ma", "{\"env\":{\"DOPPLER_TOKEN\":\"dp.ct.2El38vn53VQXAyYQ4PKUK88lpsgCM1SSYOUrI65O\"}}", "DOPPLER_TOKEN=dp.said.zxqUeHDQr0Itcdt1yZul7R81aHY7QSVMQhL8L0JOco"},
			nomatch: []string{"dp.pt.tooshort", "dp.pt.aqlb6WIuPUYGz300dACjXFomKnJmIyOsiN0sJgc", "dp.xx.aqlb6WIuPUYGz300dACjXFomKnJmIyOsiN0sJgctY0Ma"},
		},
		{
			id:      "gcp-api-key",
			match:   []string{"GOOGLE_API_KEY=AIzazyN9zHYIa4UOrGNATMuDJawTgsu8PO_799n", "{\"apiKey\": \"AIzaKSNrh9UCauSDmLhuVtcqcYezdZ-tDDj8hYs\", \"authDomain\": \"example.firebaseapp.com\"}"},
			nomatch: []string{"GOOGLE_API_KEY=AIzatooshort", "GOOGLE_API_KEY=AIza!zyN9zHYIa4UOrGNATMuDJawTgsu8PO_799n", "GOOGLE_API_KEY=xAIzazyN9zHYIa4UOrGNATMuDJawTgsu8PO_799n", "GOOGLE_API_KEY=AIzaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},
		},
		{
			id:      "generic-api-key-assignment",
			match:   []string{"export API_KEY=sk_live_9fQ2vR7wL4mN8pX1sT6bF3jH0cD5yUaZ9k", "api_key: \"aZ9kQ2vR7wL4mN8pX1sT6bF3jH0cD5yU\"", "{\"access_token\": \"Xk9mP2vQ7Rt4Ws8LbN3jF6hZ1cYdA0eB5g\"}", "secret_key_base: \"tfYGCfFfu10pV8G5gtUJ1do3LDwnu+eWBfL1sNtK8+bEwo6gNzFQZtWkdNQVlt+V\"", "SESSION_SECRET = 'C7vR2mX9qL4nP8sT1wK6jH3bF0dA5yUz'"},
			nomatch: []string{"api_key = \"your-api-key-here-1234567890\"", "client_secret: \"550e8400-e29b-41d4-a716-446655440000\"", "secret_key = \"hello_world_this_is_config\"", "secret_key_base = \"development-only-placeholder\"", "session_secret = process.env.SESSION_SECRET", "capi_key = \"randomsecretvalueXk9mP2vQ7Rt4Ws8\"", "api_key: Optional[str]", "api_key: Option<String>", "api_key=os.environ.get(\"GROQ_API_KEY\")", "api_key=process.env.GROQ_API_KEY", "api_key=${ANTHROPIC_API_KEY:-fallback}", "api_key=op://ExampleVault/Anthropic/key", "api-key: https://developers.example.invalid/docs/api-keys", "api_key=cfg.typesense_api_key", "api_key=dev_resend_api_key\\nnext_field", "client_secret=dev-client-secret", "`x_api_key=` still fires — preceding `_`", "api_key=`still fires — preceding`", "api_key=SG.Yx-zfSAN2cW7GfP6R7o425.U85hfj...", "api_key = k.cfg.DataStreamsKey", "apiKey = normalizedSecretValue"},
		},
		{
			id:      "generic-bearer-like-token-assignment",
			match:   []string{"export TOKEN=aZ9kQ2vR7wL4mN8pX1sT6bF3jH0cD5yUaZ9k", "token: \"Xk9mP2vQ7Rt4Ws8LbN3jF6hZ1cYdA0eB5gC7h\"", "{\"auth_token\": \"k3JmQz9XpL2vN7wR5tY8bC1sD4fA6hE0uI2oP\"}"},
			nomatch: []string{"token = csv.next()", "token: <YOUR_TOKEN>", "token = \"your-token-here-1234567890abcdef\"", "token: \"550e8400-e29b-41d4-a716-446655440000\"", "token = \"helloworldconfigurationvalue\"", "token = sqlc.arg(claim_token)", "token=${GIT_REPOSITORY_INTERNAL_TOKEN:-fallback}", "token=op://ExampleVault/Cloudflare/token", "token=EXCLUDED.refresh_token", "token=bearerToken(request.headers.get(\"authorization\"))", "token=var.cloudflare_api_token", "token=BASE_WATCHER_INTERNAL_API_TOKEN", "token=0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913", "token=BASE_WATCHER_INTERNAL_API_TOKEN\\\\\\\"", "`token=` pairs fire once", "token=`github_pat_` + fgpatP1b + `", "token=ntn_LFn3YnrPf6lJOdoQdQqA5zd5SriKEc8WlTo9...", "token = this.erc20ReturnFalseMock", "token: options.awsContainerAuthorizationToken", "token = originalReviewGithubToken", "use light_token::instruction::derive_token_ata;"},
		},
		{
			id:      "generic-password-assignment",
			match:   []string{"export PASSWORD=Xk9mP2vQ7Rt4Ws8Lb", "password: \"Zt7Qp2Xk9mLwR4vN8\"", "{\"pwd\": \"aZ9kQ2vR7wL4mN8pX1sT6bF3\"}"},
			nomatch: []string{"password = \"changeme\"", "passwd: \"550e8400-e29b-41d4-a716-446655440000\"", "password = \"configuration\"", "pwd", "$ pwd", "passwd: files systemd", "password=${STORAGE_SECRET_ACCESS_KEY:-fallback}", "password=String(data.get(\"password\"))", "password=op://ExampleVault/Postgres/password", "password=secret123\\nnext", "password = \"correct horse battery staple\"", "password: URLPatternComponentResult", "password = 'trimmed prose, not a credential value. '"},
		},
		{
			id:      "generic-secret-assignment",
			match:   []string{"AWS Secret Key = rwsmyxydQrWgPCi4wtEP7qi75tWU", "Client Auth Token: 9rtyiWofxFYcbVNBebGDBV2h", "key = 69cv5BW8EwnNoBtGGe8aNAHh7NWfiM1O", "{\"credential\": \"FlOJfSS2xyK7tLQh9bZU\"}", "creds=0cXGCcKnSPVS3qsTbU7H3D8YTfkFdL"},
			nomatch: []string{"keyboard shortcuts are useful for this workflow", "author = 'Alice Programmer'", "the monkey business continued for hours", "access = os.environ.get('SECRET')", "credential_id = 550e8400-e29b-41d4-a716-446655440000", "key = short", "secret = aaaaaaaaaaaaaaaaaaaaaaaaaaaa", "`key=`rwsmyxydQrWgPCi4wtEP7qi75tWU`"},
		},
		{
			id:      "github-app-token",
			match:   []string{"GITHUB_APP_USER_TOKEN=ghu_TD7USV0nSe6MVhPyD4v3RhFfioL0bco9gSiM", "installation_token: ghs_9b3mUXozvaTiZ0b6kg5jhePWvxPd3mLqzu8N"},
			nomatch: []string{"ghu_tooShort", "ghs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "ghu_TD7USV0nSe6MVhPyD4v3RhFfioL0bco9gSiM1"},
		},
		{
			id:      "github-fine-grained-pat",
			match:   []string{"GITHUB_FINE_GRAINED_PAT=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", "export TOKEN=\"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\""},
			nomatch: []string{"github_pat_pNLXUQBEWt9iBIWhqsMcTQ_short", "github_pat_pNLXUQBEWt9iBIWhqsMcTQ-iT0f4QyUrymftnlmT2umhmf7J6BgIuQ3ynO4SNP6dVUK0CcwZUvP8pmGW9F", "github_pat_xxxxxxxxxxxxxxxxxxxxxx_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "github-oauth-token",
			match:   []string{"GITHUB_OAUTH_TOKEN=gho_L2m69I7wDdQGnMo6sFSYnvCeqmkfCXIxmEYu", "{\"access_token\": \"gho_jRNwkJTQMlysNBKLcUHINVH44lVYyCoGifZd\", \"token_type\": \"bearer\"}"},
			nomatch: []string{"GITHUB_OAUTH_TOKEN=gho_tooShort123", "GITHUB_OAUTH_TOKEN=gho_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "GITHUB_OAUTH_TOKEN=gho_L2m69I7wDdQGnMo6sFSY nvCeqmkfCXIxmEYu"},
		},
		{
			id:      "github-pat",
			match:   []string{"ghp_16C7e42F292c6912E7710c838347Ae178B4a", "ghp_OhbVrpoiVgRV5IfLBcbfnoGMbJmTPSIAoCLr"},
			nomatch: []string{"ghp_short", "ghp_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "ghp_u8jzPde0IgxLd6GncfBAepfJBd0Kh8oOOL8dA", "ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghij"},
		},
		{
			id:      "github-refresh-token",
			match:   []string{"GITHUB_REFRESH_TOKEN=ghr_4LwLYg8atHXKvsk2wkW4jgQzw7k2BNy1DF43", "{\"refresh_token\":\"ghr_T5EbJ8H0Ed9ZqZemZFxBCVPsSoVDrTEPilrx\"}"},
			nomatch: []string{"GITHUB_REFRESH_TOKEN=ghr_short", "GITHUB_REFRESH_TOKEN=ghr_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "GITHUB_REFRESH_TOKEN=ghr_4LwLYg8atHXKvsk2wk W4jgQzw7k2BNy1DF43"},
		},
		{
			id:      "gitlab-deploy-token",
			match:   []string{"DEPLOY_TOKEN=gldt-KzooQLKR9hstfKw-FvxsBs2bzQFJDG0Vy9R", "docker login registry.example.com -u deploy -p gldt-Mbpq99FJ02j5iOP_hnZ4"},
			nomatch: []string{"gldt-tiny1", "gldt-abcDE12345 KzooQLKR9hstfKw-FvxsBs2bzQFJDG0Vy9R", "gldt-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "gitlab-feed-token",
			match:   []string{"https://gitlab.example.com/dashboard/projects.atom?feed_token=glft-qJqB_QybyiSr_oKMX6Sv", "GITLAB_FEED_TOKEN=glft-qJqB_QybyiSr_oKMX6Sv"},
			nomatch: []string{"glft-tooshort", "glft-abcDE12345QybyiSr_oK BO_yY1vy1Dx71XJWCS", "glft-XXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "gitlab-feed-token-v2",
			match:   []string{"https://gitlab.example.com/dashboard/projects.atom?feed_token=glft-adce58af7fb13e75e10872ccd70c698225791ea3e147cfda5d3f04e82f9badfe-12345678", "GITLAB_FEED_TOKEN=glft-ADCE58AF7FB13E75E10872CCD70C698225791EA3E147CFDA5D3F04E82F9BADFE-1"},
			nomatch: []string{"glft-adce58af7fb13e75e10872ccd70c698225791ea3e147cfda5d3f04e82f9badf-12345678", "glft-adce58af7fb13e75e10872ccd70c698225791ea3e147cfda5d3f04e82f9badfe12345678", "glft-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-12345678"},
		},
		{
			id:      "gitlab-pat",
			match:   []string{"GITLAB_PAT=glpat-BO_yY1vy1Dx71XJWCS_eOE50i2nLmR", "Authorization: Bearer glpat-9M71uUC6dXE67HSyDv5S0ZGci"},
			nomatch: []string{"glpat-abc123", "glpat-abcDE12345 BO_yY1vy1Dx71XJWCS_eOE50i2nLmR", "glpat-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "gitlab-pipeline-trigger-token",
			match:   []string{"CI_TRIGGER_TOKEN=glptt-wu8ZwMSnGykZpCGoOORMvWtoGMrPK7pI79pt3Sp5", "curl -X POST --form token=glptt-wu8ZwMSnGykZpCGoOORMvWtoGMrPK7pI79pt3Sp5 https://gitlab.example.com/api/v4/projects/1/trigger/pipeline"},
			nomatch: []string{"glptt-tooshort", "glptt-wu8ZwMSnGykZpCGoOORMvWtoGMrPK7pI79pt3Sp", "glptt-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "gitlab-runner-token",
			match:   []string{"CI_RUNNER_TOKEN=glrt-dJc9SE3diMqM_KM3RYy7XNeTwCI_", "{\"token\": \"glrt-EmRFgtLiVRnl7YoMV36D9C\"}"},
			nomatch: []string{"glrt-short1", "glrt-abcDE12345 dJc9SE3diMqM_KM3RYy7XNeTwCI_", "glrt-XXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "grafana-cloud-access-policy-token",
			match:   []string{"GRAFANA_CLOUD_TOKEN=glc_BZS9bJBlQtfU/dx9UHdyN05m/hEf3Gw7HdOQy3lyvH19ja5pvfqkcoEVULjZ", "{\"token\":\"glc_BZS9bJBlQtfU/dx9UHdyN05m/hEf3Gw7HdOQy3lyvH19ja5pvfqkcoEVULjZ==\"}"},
			nomatch: []string{"glc_tooshort", "glc_BZS9bJBlQtfU/dx9UHdyN05m/hEf3Gw7HdOQy3lyvH19ja5pvfqkcoEVULjZ==="},
		},
		{
			id:      "grafana-service-account-token",
			match:   []string{"'Authorization': 'Bearer glsa_Z3aIKXTVKpH1zp8kfsZ8XTVM62Gb02O7_2d065813'", "GRAFANA_TOKEN=glsa_hYAFlBFRud6UBH6vN1IeiYwijYiFw8Ku_E888FFC5"},
			nomatch: []string{"glsa_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_AAAAAAAA", "glsa_Z3aIKXTVKpH1zp8kfsZ8XTVM62Gb02O7_2d06581", "glsa_Z3aIKXTVKpH1zp8kfsZ8XTVM62Gb02O7-2d065813"},
		},
		{
			id:      "groq-api-key",
			match:   []string{"GROQ_API_KEY=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", "Authorization: Bearer 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", "{\"groq_api_key\": \"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\"}"},
			nomatch: []string{"gsk_short", "gsk_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "gsk_wJbCoeH86zjKgop71T4-viLZ6QRKh2kwaIp2lYCV9MiujTbzw3MA", "gsk_wJbCoeH86zjKgop71T4uviLZ6QRKh2kwaIp2lYCV9MiujTbzw3MAZ"},
		},
		{
			id:      "huggingface-token",
			match:   []string{"HUGGINGFACE_TOKEN=hf_nW2OPJ0rGsD6y4OUtEXQxmAa3BItWMoP6J", "Authorization: Bearer hf_SoSitdlyJv4jWuJOgem50hOrLw9OoFOcb4", "{\"token\": \"hf_nW2OPJ0rGsD6y4OUtEXQxmAa3BItWMoP6J\"}"},
			nomatch: []string{"hf_short", "hf_ab-cdefghijklmnopqrstuvwxyz01234", "from transformers import hf_hub_download", "hf_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "jwt",
			match:   []string{"{\"role\":\"tool\",\"content\":\"exchanged assertion eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzdmMtcmVwb3J0aW5nIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLmludGVybmFsLmV4YW1wbGUiLCJleHAiOjE3NjcyMjU2MDB9.q4TnV7bXk2LwZ9pR0sYhF6dJ1aG5uEiO8cM3rTvQ6wN\"}", "export OIDC_ID_TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6InN5bnRoZXRpYy0yMDI2In0.eyJzdWIiOiJ1c2VyLTQ4MjEiLCJzY29wZSI6InRyYW5zY3JpcHRzOnJlYWQiLCJpYXQiOjE3NTUxNzI4MDB9.Zc0vW5nRq8LtK2mXp7YbD4fH9jS1gU6eA3iO0rMwT5zVxN8cP2kEyG7uJ4hB", "2026-08-14T18:02:11Z DEBUG oauth exchange returned eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uIjoiYjFmNiJ9.N5wKp8VzR2mT7bXq0LcY4fJ6hD1gS9uE3aI", "{\"stdout\":\"introspecting eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyLTQ4MjEiLCJzY29wZSI6InRyYW5zY3JpcHRzOnJlYWQiLCJpYXQiOjE3NTUxNzI4MDB9.q4TnV7bXk2LwZ9pR0sYhF6dJ1aG5uEiO8cM3rTvQ6wN\\n\"}", "exchanged assertion eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzdmMtcmVwb3J0aW5nIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLmludGVybmFsLmV4YW1wbGUiLCJleHAiOjE3NjcyMjU2MDB9.q4TnV7bXk2LwZ9pR0sYhF6dJ1a+G5uEi/8cM3rTvQ6wN"},
			nomatch: []string{"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9", "authorization: bearer eyJhbGciOiJIUzI1NiJ9.pZ8kQ2vR7wL4mN0pX1sT.hB3jF6hZ1cYdA0eBqG", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.xxxxxxxxxxxxxxxx", "SGVyZSBpcyBzb21l.eyJub3RlIjoibm90LWEtand0In0.c2lnbmF0dXJlLWJs", "config blob eyJrZXkiOiJ2YWx1ZSJ9 is inline base64 JSON, not a JWT", "rawblob_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uIjoiYjFmNiJ9.N5wKp8VzR2mT7bXq0LcY4fJ6hD1gS9uE3aI", "eyJhbGciOiJIUzI1NiJ9.eyJhIjoxfQ.q4TnV7bXk2LwZ9pR0sYhF6dJ1aG5u"},
		},
		{
			id:      "linear-api-key",
			match:   []string{"export LINEAR_API_KEY=lin_api_FeWaVUqG2KVasfSq8Z0wjCdFUQUHxZ3g0Aq3idaD", "{\"linear_api_key\": \"lin_api_MhXnwfocwDNRjI7Sc4sfHBomzPtKTjAjaFO16Hd8Hp1Jf7tSgtRa1eePdjJY\"}"},
			nomatch: []string{"lin_api_M6mgv4I3ERxy2aV7ygR0ASuT1llqf3", "lin_api_FeWaVUqG2KVasfSq8Z0wjCdF-UQUHxZ3g0Aq3idaD", "lin_api_QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ"},
		},
		{
			id:      "notion-internal-token",
			match:   []string{"export NOTION_TOKEN=secret_JcieWVjwiYd7U3MsPkYO2xaCUvet6zYYqy0pJf9CIg9", "{\"notion_secret\": \"secret_lV3G32cGh6dAuJa3pJEeyQVnsZpF2V2r2iY9Uot4wf3\"}", "export NOTION_TOKEN=ntn_LFn3YnrPf6lJOdoQdQqA5zd5SriKEc8WlTo9bsQd2TMY2e", "{\"notion_token\": \"ntn_GPYkWkSsSB1qZRAk3rxvD6mvf155SxzOmzWOoMnQrwuxqr1IoG5opCTycClX\"}"},
			nomatch: []string{"the client_secret_JcieWVjwiYd7U3MsPkYO2xaCUvet6zYYqy0pJf9CIg9 field", "token=secret_iCnEPor6SOvFbGwot3GcKsT5BCUyDSWXbJPhakryLK", "token=ntn_uIF6SUvaLMIyi4Xhg6R1KQ608e9zSv3VzHd9EJw9O3rur"},
		},
		{
			id:      "npm-access-token",
			match:   []string{"NPM_TOKEN=npm_plknz1kJAShTH8KvwDZPcixBekByPBAakTBO", "//registry.npmjs.org/:_authToken=npm_TOltgSxsXbtv4bMFG9MvKZHj0LRUG1a6nKiZ"},
			nomatch: []string{"npm_config_registry=https://registry.npmjs.org/", "npm_config_yes=true", "NPM_TOKEN=npm_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "NPM_TOKEN=npm_short"},
		},
		{
			id:      "openai-legacy-key",
			match:   []string{"OPENAI_API_KEY=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", "Authorization: Bearer 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", "{\"key\": \"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\"}"},
			nomatch: []string{"sk-abcdEFGH12", "sk-70Ii88WRAFMcMAhCWPfOagj8Ggq8MY8sbFU24lQSbfFBDwJn", "Authorization: Bearer sk-ant-api03-L6VtNHDzbvOYIs52KThe1DBzYMxIsTnjxqnzKJgS1niDgzJKhy20RHoBqBbuVcPjhcUAwu89LeznSyn2bpa26sQIrfAA", "OPENAI_API_KEY=sk-proj-BVNMKlvU9FzBvWdqOPDZtJVcBIS5TvkvuzSLy8asT3BlbkFJLq83zMskErFlHpuT9KMBRkPgrihZPskJwst1ctDX", "This model carries elevated risk-taking behavior in production."},
		},
		{
			id:      "openai-project-key",
			match:   []string{"OPENAI_API_KEY=sk-proj-BVNMKlvU9FzBvWdqOPDZtJVcBIS5TvkvuzSLy8asT3BlbkFJLq83zMskErFlHpuT9KMBRkPgrihZPskJwst1ctDX", "Authorization: Bearer sk-svcacct-4zROgBOLNt0ZP9sqaEZXj8WJxMSWeuquxqsQX6zBjK1bJpnvzDHlclD7U6Ro", "{\"config\": {\"openai_key\": \"sk-admin-4zROgBOLNt0ZP9sqaEZXj8WJxMSWeuquxqsQX6zBjK1bJpnvzDHlclD7U6Ro\"}}"},
			nomatch: []string{"sk-proj-0JBJkQfgbsuTgzoeHx6jHkf5g1sKJ2", "sk-svcacct-abc$%^&*()", "sk-admin-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "The vendor's risk-proj-ection model still relies on legacy tools."},
		},
		{
			id:      "pem-private-key",
			match:   []string{"-----BEGIN OPENSSH PRIVATE KEY-----\nrpvGMXOAKGX6B+kpekdCsOtzCoV+ZuCNdBcPTT9hA6rOjKjGc6MefdDU8p5oXcY7\nrmqoDH0qVi/huXgpY1qHTa43gddwT5TXFrrNosHPdl19o2Z+/7piAa2GqytsZN3C\n2uCmH6CHd67YEB0uS5MMuWrzaXnJ0gfBwd91bSrUJj9LZRsK1PbRQUyZJjzlxYuw\n75dnx5rqKXyLS8Zhms26Wg==\n-----END OPENSSH PRIVATE KEY-----\n", "-----BEGIN RSA PRIVATE KEY-----\n+d8lz6RCC7suHWdngVelufP37AbgZFNOdJDmYi8VNuz6KOrxYDc15SKUJi+H3/sV\nJNHCUb7b3BpnOGRLa+2yMuias21KPFR8Axm4JzRUdrDSzQz+J0dAs2b7Dic7gm2O\nHwdixVZHihKkCBzhlDoM4CMLCKwn83R/n895ffXcXqy9pHuEd0qu9765175ufW5h\n-----END RSA PRIVATE KEY-----\n", "{\"event\":\"agent_exec\",\"secret\":\"-----BEGIN OPENSSH PRIVATE KEY-----\\nMPjfSFCnwhGTQ+Nb7jYRFRuaHWmQZy/qYe4benpW2R0Ipl3erdPWAsL8ju10Qwgr\\nFBwciFpPb32JqfTqqxEhjtg47xRCoOfQbEJfUzmdn52uzmNOJqnmNKCyiLf9QWsq\\n-----END OPENSSH PRIVATE KEY-----\\n\"}", "-----BEGIN RSA PRIVATE KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: AES-128-CBC,A1B2C3D4E5F60718293A4B5C6D7E8F90\n\ntLQfbEBiLk97Gc+CQPmipyAB7Ve5n/Vw+LWbnt0ao6mWMkOGu4gFlxRMIzmEBqeo\n6jNqZ5NfymdkR6RBmPsCQ9qLSdrpmeeEsJS0XG6On2Vu+B2s17OWsV0yKXc0ubiG\n-----END RSA PRIVATE KEY-----\n", "-----BEGIN PRIVATE KEY-----\npXIKj1muE8wjxUB4P1NbhSPqyP1epR04JEmb6DTk/MjMhfvfk9bIc/z+mHPIuvz/\n2xmt9Ru7t5EBG+JmdLz4/hKQL6tv1KsQb7VSpSIMeFwomJ620IQMBajXgnRC8f0w\nYmicg//E+BFDyb76VongDyy7sllrDOdbcTeMkg5yJvwRQXxIaYNi0BhkMfrL08Lz", "{\"tool_result\": \"{\\\"output\\\": \\\"-----BEGIN RSA PRIVATE KEY-----\\\\nrpvGMXOAKGX6B+kpekdCsOtzCoV+ZuCNdBcPTT9hA6rOjKjGc6MefdDU8p5oXcY7\\\\n2uCmH6CHd67YEB0uS5MMuWrzaXnJ0gfBwd91bSrUJj9LZRsK1PbRQUyZJjzlxYuw\\\\n-----END RSA PRIVATE KEY-----\\\\n\\\"}\"}"},
			nomatch: []string{"-----BEGIN CERTIFICATE-----\nFc6xc4/fGGyOOMLU524WciLQYdWNI1g0r0yU5Zt2vWuLiLGoL4my/oP7adWIj2Rk\n-----END CERTIFICATE-----\n", "-----BEGIN PUBLIC KEY-----\nDgTef9Rdy/5scNY8uQgLKB9qLJNYHnvJ51I7WIcAmgkh28NbBFn9gqwcO8ma5pJ9\n-----END PUBLIC KEY-----\n", "-----BEGIN PRIVATE KEY----- is the PEM header", "-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----\n"},
		},
		{
			id:      "putty-private-key",
			match:   []string{"PuTTY-User-Key-File-2: ssh-rsa\nEncryption: none\nComment: synthetic-fixture\nPublic-Lines: 2\nJNHCUb7b3BpnOGRLa+2yMuias21KPFR8Axm4JzRUdrDSzQz+J0dAs2b7Dic7gm2O\nHwdixVZHihKkCBzhlDoM4CMLCKwn83R/n895ffXcXqy9pHuEd0qu9765175ufW5h\nPrivate-Lines: 2\ntLQfbEBiLk97Gc+CQPmipyAB7Ve5n/Vw+LWbnt0ao6mWMkOGu4gFlxRMIzmEBqeo\n6jNqZ5NfymdkR6RBmPsCQ9qLSdrpmeeEsJS0XG6On2Vu+B2s17OWsV0yKXc0ubiG\nPrivate-MAC: 6f1c2b3a4d5e6f708192a3b4c5d6e7f8091a2b3c\n", "PuTTY-User-Key-File-3: ssh-ed25519\nEncryption: none\nComment: synthetic-truncated\nPublic-Lines: 1\nFc6xc4/fGGyOOMLU524WciLQYdWNI1g0r0yU5Zt2vWuLiLGoL4my/oP7adWIj2Rk\nPrivate-Lines: 6\nrpvGMXOAKGX6B+kpekdCsOtzCoV+ZuCNdBcPTT9hA6rOjKjGc6MefdDU8p5oXcY7\nrmqoDH0qVi/huXgpY1qHTa43gddwT5TXFrrNosHPdl19o2Z+"},
			nomatch: []string{"PuTTY-User-Key-File-9: ssh-rsa\nEncryption: none\nPrivate-Lines: 1\npXIKj1muE8wjxUB4P1NbhSPqyP1epR04JEmb6DTk/MjMhfvfk9bIc/z+mHPIuvz/\n", "PuTTY-User-Key-File-2: ssh-rsa\nEncryption: none\nComment: public-only\nPublic-Lines: 1\nDgTef9Rdy/5scNY8uQgLKB9qLJNYHnvJ51I7WIcAmgkh28NbBFn9gqwcO8ma5pJ9\n", "the PuTTY-User-Key-File-2 format stores Private-Lines: 14 body lines"},
		},
		{
			id:      "pypi-api-token",
			match:   []string{"PYPI_API_TOKEN=pypi-AgEIcHlwaS5vcmciP1aKP8I598r9hDBybMnEIx9dj0L-mNSWyd04f1Ibz0rFbGOnIRyMex-3LajVwjAeU-5aeC_7TS", "twine upload --repository pypi --password pypi-Kx3nk2FwGJA8cZG3hRAq7b_1nfEB9W8xiavowuP8SWVADE1tXNac50deIoGvPKXvSt3lTrHxfFid0utBAisqoF_I6b6SFx4fDBmH dist/*"},
			nomatch: []string{"pypi-tooShortToken1234567890", "pypi-abcDE12345 Fy7lOBCGPVunOMqKKLByo2Azdma5XY3XWladYTLBrX1P9HS2JJWJTgPCEQQLtkaREmFr1hs7k7dnztUQC9AsSxYc1x", "pypi-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "sendgrid-api-key",
			match:   []string{"curl -H \"Authorization: Bearer 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\" https://api.sendgrid.com/v3/mail/send", "SENDGRID_API_KEY=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"},
			nomatch: []string{"SG.ci3_DxrzV7QDyDK2R7XGh.wpb6prwj1gK8CGscIFDfZCTeQ8Ob7gvVOUnNDnwyZJf", "SG.OhWhEN3so3OxYgF3AZu3Iq.oPmn0pzlQY1wWmzAmka p744b8VKkqLencZSDFf8J61", "the MSG.OhWhEN3so3OxYgF3AZu3Iq.oPmn0pzlQY1wWmzAmka3p744b8VKkqLencZSDFf8J61 was logged"},
		},
		{
			id:      "slack-app-token",
			match:   []string{"export SLACK_APP_TOKEN=xapp-1-GPMM82I1LR3-3178108013267-f6c15c0c8e9df469611a11f5125227c3712da86a78c49ea20e32684b27b95e90", "{\"app_token\": \"xapp-2-9TGIQHG9JR-4935348740-2d810a485ed03241b4d419b1b673bd4755d05ad7853c1f76eb97706ca828bca0\"}"},
			nomatch: []string{"xapp-1-ABC-123", "xapp-AAAAAAAAAAAAAAAAAAAA-BBBBBBBBBBBBBBBBBBBBBB", "xapp------------------------------------------"},
		},
		{
			id:      "slack-bot-token",
			match:   []string{"xoxb-0265423511615-5940781618495-KmTecQoXsf2o3gyrDO1xkxwnQrS7RP"},
			nomatch: []string{"xoxb-123-456-abcdefgh", "xoxb-0265423511615-5940781618495-aaaaaaaaaaaaaaaaaaaaaaaaaaaa", "xoxb-99603082462819-48219935181-KdNnFRIBXuDL7DxtpYlSXpfKtHF4", "xoxb-1234567890-1234567890123-k4Jm8nR2pX6sW9vB3fH7aT1q"},
		},
		{
			id:      "slack-user-token",
			match:   []string{"export SLACK_USER_TOKEN=xoxa-80184514627-048281489325-wKi9x7h6AmUfBH7X41zTPDP4k8FFuf", "{\"token\": \"xoxp-1822782489-63834657871-331509839301-1721a278f64f7fd633dbdde1\"}"},
			nomatch: []string{"xoxa-123-456-abcdefgh0123456789abcd", "xoxa-80184514627-048281489325-rppGDZuVz3", "xoxa-80184514627-048281489325-aaaaaaaaaaaaaaaaaaaaaaaaaaaa"},
		},
		{
			id:      "stripe-ephemeral-key",
			match:   []string{"STRIPE_EPHEMERAL_KEY=ek_test_PE3RB812Fhej8HGrwfoGMxAc1AiQ9Ac5SIrOH4hKpqJt6k385lXWq8l1LbinwrlIQMHyBrqT0HlFM7Wvs-6GG", "{\"ephemeralKey\": \"ek_live_vTh-0uCGqK6CHMwswkiIKtTDEcZp2OWJzmp1E8QW9DwUaK-En2mMSfw9SZgQClLRT\"}"},
			nomatch: []string{"ek_test_tooshort", "ek_live_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "stripe-secret-key",
			match:   []string{"curl https://api.stripe.com/v1/charges -u sk_live_oHBvRPOIvGrv5iFlbCBFNOgmBjMtpsia:", "STRIPE_SECRET_KEY=sk_test_OclRz3AwzKsbVRJN9wVGFYGW"},
			nomatch: []string{"sk_live_2WmQzCudiH", "sk_live_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "sk_live_oHBvRPOIvGrv5iFlbCBF-NOgmBjMtpsia"},
		},
		{
			id:      "stripe-webhook-secret",
			match:   []string{"STRIPE_WEBHOOK_SECRET=whsec_7YFjS1on43XkMtECqOxSF2O3GYRdo1XKXWNqRs7r", "{\"stripe_webhook_secret\": \"whsec_pEmoKiuPKdYR7osjOrU1xxDO0CzUZREN68k4tUNpfZ46pdJQIPvjiQvlb5lZXOIg\"}"},
			nomatch: []string{"whsec_fFwD3HJoKyrbmEYYmdhQ", "whsec_ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", "whsec_7YFjS1on43XkMtECqOx_SF2O3GYRdo1XKXWNqRs7r"},
		},
		{
			id:      "supabase-service-role-key",
			match:   []string{"{\"env\":{\"SUPABASE_SERVICE_ROLE_KEY\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiY2RlZmdoaWprbG1ub3AiLCJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNzAwMDAwMDAwLCJleHAiOjIwMTUzNTY4MDB9.TsKdOf3JR-kSPIbMXpSE2IlyTs8tIAGHgmy-qA5m_Xc\"}}", "export SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiY2RlZmdoaWprbG1ub3AiLCJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNzAwMDAwMDAwLCJleHAiOjIwMTUzNTY4MDB9.TsKdOf3JR-kSPIbMXpSE2IlyTs8tIAGHgmy-qA5m_Xc", "2026-08-14T18:02:11Z DEBUG creating admin client with key eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjogInNlcnZpY2Vfcm9sZSIsICJpc3MiOiAic3VwYWJhc2UiLCAicmVmIjogImFiY2RlZmdoaWprbG1ub3AiLCAiaWF0IjogMTcwMDAwMDAwMCwgImV4cCI6IDIwMTUzNTY4MDB9.EbrK-izzHh_fuSf8Ubf5ItUGm0ZkL0-HuL6cVkAnoqs"},
			nomatch: []string{"export SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiY2RlZmdoaWprbG1ub3AiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTcwMDAwMDAwMCwiZXhwIjoyMDE1MzU2ODAwfQ.EbrK-izzHh_fuSf8Ubf5ItUGm0ZkL0-HuL6cVkAnoqs", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiY2RlZmdoaWprbG1ub3AiLCJpYXQiOjE3MDAwMDAwMDAsImV4cCI6MjAxNTM1NjgwMH0.TsKdOf3JR-kSPIbMXpSE2IlyTs8tIAGHgmy-qA5m_Xc", "{\"role\":\"tool\",\"content\":\"exchanged assertion eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzdmMtcmVwb3J0aW5nIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLmludGVybmFsLmV4YW1wbGUiLCJleHAiOjE3NjcyMjU2MDB9.q4TnV7bXk2LwZ9pR0sYhF6dJ1aG5uEiO8cM3rTvQ6wN\"}"},
		},
		{
			id:      "terraform-cloud-api-token",
			match:   []string{"export TF_TOKEN_app_terraform_io=fbWTHJCs5eFRVZ.atlasv1.Hfk1htnZr3dfRKIbAPeW6N9c54fl9W2Fmz9c238OBYbOQjsfVeZdWc45s-4D3q2K", "{\"credentials\":{\"app.terraform.io\":{\"token\":\"msXQyb5HRPrMMQ.atlasv1.mNUJ4o7L_-RfvuZfhMuTfHRLuKpG3tDejyK9pTLdUSl_Vq6wdBNoGaf-TyrN1Djzdd-Jsm\"}}}"},
			nomatch: []string{"7Tbh35JCAso6J7.atlasv1.-iQdD5veIiTfY02uKTx4ioKi7IOLaIhbbUuYTN_ZEvWVYPknt1z18SGmNFP", "short.atlasv1.Hfk1htnZr3dfRKIbAPeW6N9c54fl9W2Fmz9c238OBYbOQjsfVeZdWc45s-4D3q2K"},
		},
		{
			id:      "twilio-api-key-sid",
			match:   []string{"export TWILIO_API_KEY_SID=SK3931bdb2a0df3dbe4d58fed8a728e7ec", "{\"api_key_sid\": \"SKa0fa5f6b8a880627df7ffe0297c79bfb\"}"},
			nomatch: []string{"SKDABE898736A3566F893697B590481194", "SKf309ffea518f32cf21449273d7cee9", "the TASKd9136682575250def91799e2786d3748 list", "clean the DESK421599e3e9c8fe21da80270815fe85df now"},
		},
		{
			id:      "url-credentials",
			match:   []string{"DATABASE_URL=postgres://svc_user:wZ8kQ3vR7pL4mN2x@db.internal:5432/app", "redis://:q8LmPz31vTk@cache.prod.svc:6379/0", "{\"msg\":\"connecting\",\"dsn\":\"mysql://root:Vt5xK8nQ2wZ7@10.0.0.12:3306/orders\"}", "amqps://ingest:R7pL4mN2xT6b@mq.internal:5671/%2Fprod"},
			nomatch: []string{"https://deploy@github.com/org/repo.git", "postgres://user:password@localhost:5432/db", "postgres://user:content@localhost:5432/db", "https://user:TOKEN@github.com/owner/repo.git", "postgres://user:unterminated%zz@localhost/db", "see http://user:pass@host.example.com for the URL shape", "redis://:@cache.internal:6379", "note: the \"://\" separator splits scheme from authority", "https://status.example.com/healthz", "https://git:ghp_abc123@github.com/org/repo.git", "https://user:REDACTED@github.com/org/repo.git", "postgres://app:$DB_PASSWORD@db:5432/app"},
		},
		{
			id:      "vault-batch-token",
			match:   []string{"export VAULT_TOKEN=hvb.KpG3tDejyK9pTLdUSl_Vq6wdBNoGaf-TyrN1Djzdd-Jsmdo41LD-iQdD5veIiTfY02uKTx4ioKi7IOLaIhbbUuYTN_ZEvWVYPknt1z18SGmNFPdLIcySo_hlQZbpcUeroBfki2yLt1qc6PCYFQP79YcXeDLgtjFOrVEiHuAPOAJFIuaiduxuRQ4I_QWODAAReCfDLkkR"},
			nomatch: []string{"hvb.tooshort"},
		},
		{
			id:      "vault-service-token",
			match:   []string{"export VAULT_TOKEN=hvs.ld4Ki-Hfk1htnZr3dfRKIbAPeW6N9c54fl9W2Fmz9c238OBYbOQjsfVeZdWc45s-4D3q2KyKXcJmNUJ4o7L_-RfvuZfhMuTfHRLu", "{\"auth\":{\"client_token\":\"hvs.nssrJa6yw4IUk6yEu4d-yIVGKpG3tDejyK9pTLdUSl_Vq6wdBNoGaf-TyrN1Djzdd-Jsmdo41LD-iQdD5v\"}}"},
			nomatch: []string{"hvs.tooshort", "hvs.XXXXXXXXXXXXXXXXXXXXXXXX"},
		},
		{
			id:      "vercel-legacy-token",
			match:   []string{"export VERCEL_TOKEN=uNEcIzRFpJA7ZAhnkQlPaSrk", "VERCEL_API_TOKEN: \"whAOs0PHRVc7baApD22pdq3K\"", "{\"vercel_token\": \"uNEcIzRFpJA7ZAhnkQlPaSrk\"}"},
			nomatch: []string{"VERCEL_TOKEN=tooshort", "VERCEL_TOKEN=uNEcIzRFpJA7ZAhnkQlPaSr"},
		},
		{
			id:      "vercel-token",
			match:   []string{"export VERCEL_TOKEN=vcp_tiiXNZJG8PWIe46dxHIq2gFIpt4MOdHahokWEFbt6quMzOwFgxK7fO1V", "{\"apiKey\":\"vck_Ro7FlIEcfF9XCDS72kuexw3cmaj7C3sksYpS1YAGv310BadLHjBmaQg2NCrFcQHns\"}"},
			nomatch: []string{"vcp_tooshort", "vcp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.id, func(t *testing.T) {
			rule, ok := generatedFixtureRule(tc.id)
			if !ok {
				t.Fatalf("rule %q not registered in Builtins()", tc.id)
			}
			for _, fx := range tc.match {
				if !generatedFixtureConfirms(rule, fx) {
					t.Errorf("rule %q: match fixture %q: want a trigger occurrence to validate, none did", tc.id, fx)
				}
			}
			for _, fx := range tc.nomatch {
				if generatedFixtureConfirms(rule, fx) {
					t.Errorf("rule %q: nomatch fixture %q: want no trigger occurrence to validate, one did", tc.id, fx)
				}
			}
		})
	}
}

// generatedFixtureRule, generatedFixtureConfirms, and their helpers below
// are static: their code does not depend on the specs, only on the
// (id, match, nomatch) table above, so they are byte-identical across
// regenerations that don't change the rulegen version.

func generatedFixtureRule(id string) (Rule, bool) {
	for _, r := range Builtins() {
		if r.ID == id {
			return r, true
		}
	}
	return Rule{}, false
}

// generatedFixtureConfirms reports whether at least one occurrence of one
// of rule's triggers within data is confirmed by rule.Validate, using the
// window rule.MaxLookbehind/MaxLookahead would produce at that offset
// (clamped to data's bounds).
func generatedFixtureConfirms(rule Rule, data string) bool {
	b := []byte(data)
	for _, trig := range rule.Triggers {
		for _, occ := range generatedFindOccurrences(b, trig) {
			lo := occ.start - rule.MaxLookbehind
			if lo < 0 {
				lo = 0
			}
			hi := occ.end + rule.MaxLookahead
			if hi > len(b) {
				hi = len(b)
			}
			window := b[lo:hi]
			ts, te := occ.start-lo, occ.end-lo
			if _, _, ok := rule.Validate(window, ts, te); ok {
				return true
			}
		}
	}
	return false
}

type generatedOccurrence struct{ start, end int }

// generatedFindOccurrences returns every occurrence (including overlapping
// ones) of trig.Literal in data, honoring trig.CaseFold with the ASCII
// case folding rule from docs/DESIGN.md (fold 'A'-'Z' to lowercase on both
// sides).
func generatedFindOccurrences(data []byte, trig Trigger) []generatedOccurrence {
	lit := []byte(trig.Literal)
	if len(lit) == 0 || len(lit) > len(data) {
		return nil
	}
	var out []generatedOccurrence
	for i := 0; i+len(lit) <= len(data); i++ {
		if generatedASCIIEqualFold(data[i:i+len(lit)], lit, trig.CaseFold) {
			out = append(out, generatedOccurrence{start: i, end: i + len(lit)})
		}
	}
	return out
}

func generatedASCIIEqualFold(a, b []byte, caseFold bool) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		ac, bc := a[i], b[i]
		if caseFold {
			ac = generatedASCIIFoldByte(ac)
			bc = generatedASCIIFoldByte(bc)
		}
		if ac != bc {
			return false
		}
	}
	return true
}

func generatedASCIIFoldByte(c byte) byte {
	if c >= 'A' && c <= 'Z' {
		return c - 'A' + 'a'
	}
	return c
}
