package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"text/template"
)

// genRule is the sorted, validated, codegen-ready form of a specRule.
type genRule struct {
	ID            string
	Name          string
	Triggers      []specTrigger
	Validator     string
	MinProfile    string // "fast" | "balanced" | "deep"
	Confidence    string // "low" | "medium" | "high"
	MaxLookbehind int
	MaxLookahead  int
	Provenance    specProvenance
	Fixtures      specFixtures
}

var (
	minProfileConst = map[string]string{
		"fast":     "ProfileFast",
		"balanced": "ProfileBalanced",
		"deep":     "ProfileDeep",
	}
	confidenceConst = map[string]string{
		"low":    "ConfidenceLow",
		"medium": "ConfidenceMedium",
		"high":   "ConfidenceHigh",
	}
)

func (r genRule) MinProfileConst() string { return minProfileConst[r.MinProfile] }
func (r genRule) ConfidenceConst() string { return confidenceConst[r.Confidence] }

// toGenRules converts validated spec rules into genRules sorted by ID. The
// sort makes the emitted table's order depend only on rule IDs, never on
// which spec file a rule happened to be declared in or its position within
// that file — so adding an unrelated rule elsewhere cannot reorder existing
// entries.
func toGenRules(rules []specRule) []genRule {
	out := make([]genRule, len(rules))
	for i, r := range rules {
		out[i] = genRule{
			ID:            r.ID,
			Name:          r.Name,
			Triggers:      r.Triggers,
			Validator:     r.Validator,
			MinProfile:    r.MinProfile,
			Confidence:    r.Confidence,
			MaxLookbehind: r.MaxLookbehind,
			MaxLookahead:  r.MaxLookahead,
			Provenance:    r.Provenance,
			Fixtures:      r.Fixtures,
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

// canonicalRule/canonicalTrigger are the JSON shape hashed to derive
// rules.Version. Only fields that appear in the emitted Go rule table
// participate: provenance and fixtures are documentation/test data, not
// part of the rule's runtime behavior, so they are deliberately excluded —
// Version changes exactly when the generated RegisterBuiltins table
// changes.
type canonicalRule struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Triggers      []canonicalTrigger `json:"triggers"`
	Validator     string             `json:"validator"`
	MinProfile    string             `json:"minProfile"`
	Confidence    string             `json:"confidence"`
	MaxLookbehind int                `json:"maxLookbehind"`
	MaxLookahead  int                `json:"maxLookahead"`
}

type canonicalTrigger struct {
	Literal  string `json:"literal"`
	CaseFold bool   `json:"caseFold"`
}

// computeVersion derives the rules.Version string from rules, which must
// already be sorted by ID. The result is stable across runs for the same
// rule content and changes whenever any rule's ID, name, triggers,
// validator, profile, confidence, or window bounds change.
func computeVersion(rules []genRule) (string, error) {
	canon := make([]canonicalRule, len(rules))
	for i, r := range rules {
		trigs := make([]canonicalTrigger, len(r.Triggers))
		for j, t := range r.Triggers {
			trigs[j] = canonicalTrigger{Literal: t.Literal, CaseFold: t.CaseFold}
		}
		canon[i] = canonicalRule{
			ID:            r.ID,
			Name:          r.Name,
			Triggers:      trigs,
			Validator:     r.Validator,
			MinProfile:    r.MinProfile,
			Confidence:    r.Confidence,
			MaxLookbehind: r.MaxLookbehind,
			MaxLookahead:  r.MaxLookahead,
		}
	}
	data, err := json.Marshal(canon)
	if err != nil {
		return "", fmt.Errorf("marshaling canonical rule table: %w", err)
	}
	sum := sha256.Sum256(data)
	return "builtin-" + hex.EncodeToString(sum[:])[:12], nil
}

const rulesFileTemplate = `// Code generated by rulegen from internal/rules/specs. DO NOT EDIT.

package rules

import "github.com/lastpersonlabs/goredact/internal/rules/validators"

// Version identifies the built-in rule-set revision. It is the first 12
// hex characters of the SHA-256 digest of the canonical serialization of
// the generated rule table below (see tools/rulegen), so it changes
// exactly when the generated rules change.
const Version = "{{.Version}}"

func init() {
	RegisterBuiltins([]Rule{
{{range .Rules}}		{
			ID:   {{printf "%q" .ID}},
			Name: {{printf "%q" .Name}},
			Triggers: []Trigger{
{{range .Triggers}}				{Literal: {{printf "%q" .Literal}}, CaseFold: {{.CaseFold}}},
{{end}}			},
			Validate:      validators.{{.Validator}},
			MinProfile:    {{.MinProfileConst}},
			Confidence:    {{.ConfidenceConst}},
			MaxLookbehind: {{.MaxLookbehind}},
			MaxLookahead:  {{.MaxLookahead}},
		},
{{end}}	})
}
`

const fixturesFileTemplate = `// Code generated by rulegen from internal/rules/specs. DO NOT EDIT.
//
// Provenance:
{{range .Rules}}//   {{.ID}}: {{.Provenance.Source}} ({{.Provenance.License}})
{{end}}
package rules

import "testing"

// TestGeneratedRuleFixtures confirms that every match fixture in
// internal/rules/specs is confirmed by its rule's Validate at some trigger
// occurrence, and that every nomatch fixture is confirmed at none.
func TestGeneratedRuleFixtures(t *testing.T) {
	cases := []struct {
		id      string
		match   []string
		nomatch []string
	}{
{{range .Rules}}		{
			id:      {{printf "%q" .ID}},
			match:   []string{ {{range .Fixtures.Match}}{{printf "%q" .}}, {{end}} },
			nomatch: []string{ {{range .Fixtures.NoMatch}}{{printf "%q" .}}, {{end}} },
		},
{{end}}	}

	for _, tc := range cases {
		t.Run(tc.id, func(t *testing.T) {
			rule, ok := generatedFixtureRule(tc.id)
			if !ok {
				t.Fatalf("rule %q not registered in Builtins()", tc.id)
			}
			for _, fx := range tc.match {
				if !generatedFixtureConfirms(rule, fx) {
					t.Errorf("rule %q: match fixture %q: want a trigger occurrence to validate, none did", tc.id, fx)
				}
			}
			for _, fx := range tc.nomatch {
				if generatedFixtureConfirms(rule, fx) {
					t.Errorf("rule %q: nomatch fixture %q: want no trigger occurrence to validate, one did", tc.id, fx)
				}
			}
		})
	}
}

// generatedFixtureRule, generatedFixtureConfirms, and their helpers below
// are static: their code does not depend on the specs, only on the
// (id, match, nomatch) table above, so they are byte-identical across
// regenerations that don't change the rulegen version.

func generatedFixtureRule(id string) (Rule, bool) {
	for _, r := range Builtins() {
		if r.ID == id {
			return r, true
		}
	}
	return Rule{}, false
}

// generatedFixtureConfirms reports whether at least one occurrence of one
// of rule's triggers within data is confirmed by rule.Validate, using the
// window rule.MaxLookbehind/MaxLookahead would produce at that offset
// (clamped to data's bounds).
func generatedFixtureConfirms(rule Rule, data string) bool {
	b := []byte(data)
	for _, trig := range rule.Triggers {
		for _, occ := range generatedFindOccurrences(b, trig) {
			lo := occ.start - rule.MaxLookbehind
			if lo < 0 {
				lo = 0
			}
			hi := occ.end + rule.MaxLookahead
			if hi > len(b) {
				hi = len(b)
			}
			window := b[lo:hi]
			ts, te := occ.start-lo, occ.end-lo
			if _, _, ok := rule.Validate(window, ts, te); ok {
				return true
			}
		}
	}
	return false
}

type generatedOccurrence struct{ start, end int }

// generatedFindOccurrences returns every occurrence (including overlapping
// ones) of trig.Literal in data, honoring trig.CaseFold with the ASCII
// case folding rule from docs/DESIGN.md (fold 'A'-'Z' to lowercase on both
// sides).
func generatedFindOccurrences(data []byte, trig Trigger) []generatedOccurrence {
	lit := []byte(trig.Literal)
	if len(lit) == 0 || len(lit) > len(data) {
		return nil
	}
	var out []generatedOccurrence
	for i := 0; i+len(lit) <= len(data); i++ {
		if generatedASCIIEqualFold(data[i:i+len(lit)], lit, trig.CaseFold) {
			out = append(out, generatedOccurrence{start: i, end: i + len(lit)})
		}
	}
	return out
}

func generatedASCIIEqualFold(a, b []byte, caseFold bool) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		ac, bc := a[i], b[i]
		if caseFold {
			ac = generatedASCIIFoldByte(ac)
			bc = generatedASCIIFoldByte(bc)
		}
		if ac != bc {
			return false
		}
	}
	return true
}

func generatedASCIIFoldByte(c byte) byte {
	if c >= 'A' && c <= 'Z' {
		return c - 'A' + 'a'
	}
	return c
}
`

// renderRulesFile renders and gofmt-formats zz_generated_rules.go for the
// given (already sorted) rules and version string.
func renderRulesFile(rules []genRule, version string) ([]byte, error) {
	tmpl, err := template.New("rules").Parse(rulesFileTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing rules template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, struct {
		Version string
		Rules   []genRule
	}{Version: version, Rules: rules}); err != nil {
		return nil, fmt.Errorf("rendering rules file: %w", err)
	}
	out, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt on generated rules file: %w\n%s", err, buf.String())
	}
	return out, nil
}

// renderFixturesFile renders and gofmt-formats
// zz_generated_fixtures_test.go for the given (already sorted) rules.
func renderFixturesFile(rules []genRule) ([]byte, error) {
	tmpl, err := template.New("fixtures").Parse(fixturesFileTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing fixtures template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, struct{ Rules []genRule }{Rules: rules}); err != nil {
		return nil, fmt.Errorf("rendering fixtures file: %w", err)
	}
	out, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt on generated fixtures file: %w\n%s", err, buf.String())
	}
	return out, nil
}
