package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func runGen(t *testing.T, specsDir string) (rulesSrc, fixturesSrc []byte, err error) {
	t.Helper()
	dir := t.TempDir()
	outPath := filepath.Join(dir, "zz_generated_rules.go")
	fixturesPath := filepath.Join(dir, "zz_generated_fixtures_test.go")

	err = run(specsDir, outPath, fixturesPath)
	if err != nil {
		return nil, nil, err
	}
	rulesSrc, rerr := os.ReadFile(outPath)
	if rerr != nil {
		t.Fatalf("reading generated rules file: %v", rerr)
	}
	fixturesSrc, ferr := os.ReadFile(fixturesPath)
	if ferr != nil {
		t.Fatalf("reading generated fixtures file: %v", ferr)
	}
	return rulesSrc, fixturesSrc, nil
}

func TestValidSpecsGenerateSuccessfully(t *testing.T) {
	rulesSrc, fixturesSrc, err := runGen(t, "testdata/valid/specs")
	if err != nil {
		t.Fatalf("run() error = %v, want nil", err)
	}
	for _, want := range []string{
		"Code generated by rulegen",
		"DO NOT EDIT",
		"package rules",
		`const Version = "builtin-`,
		"func init() {",
		"RegisterBuiltins([]Rule{",
		"validators.FakeValidatorA",
		"validators.FakeValidatorB",
		"validators.FakeValidatorC",
	} {
		if !bytes.Contains(rulesSrc, []byte(want)) {
			t.Errorf("generated rules file missing %q\n---\n%s", want, rulesSrc)
		}
	}

	// Rules must be emitted sorted by ID: aaa-first, mmm-middle, zzz-last,
	// regardless of file/declaration order in the specs (zzz-last is
	// declared before aaa-first in a.json, and mmm-middle lives in a
	// separate file, b.json).
	src := string(rulesSrc)
	iAAA := strings.Index(src, `ID:   "aaa-first"`)
	iMMM := strings.Index(src, `ID:   "mmm-middle"`)
	iZZZ := strings.Index(src, `ID:   "zzz-last"`)
	if iAAA < 0 || iMMM < 0 || iZZZ < 0 {
		t.Fatalf("expected all three rule IDs present in generated source")
	}
	if !(iAAA < iMMM && iMMM < iZZZ) {
		t.Errorf("rules not emitted in ID-sorted order: aaa@%d mmm@%d zzz@%d", iAAA, iMMM, iZZZ)
	}

	for _, want := range []string{
		"Code generated by rulegen",
		"DO NOT EDIT",
		"package rules",
		"TestGeneratedRuleFixtures",
		`"aaa-first"`,
		`"mmm-middle"`,
		`"zzz-last"`,
		"https://example.com/aaa",
		"https://example.com/mmm",
		"https://example.com/zzz",
	} {
		if !bytes.Contains(fixturesSrc, []byte(want)) {
			t.Errorf("generated fixtures file missing %q\n---\n%s", want, fixturesSrc)
		}
	}
}

func TestGenerationIsDeterministic(t *testing.T) {
	rulesSrc1, fixturesSrc1, err := runGen(t, "testdata/valid/specs")
	if err != nil {
		t.Fatalf("first run() error = %v", err)
	}
	rulesSrc2, fixturesSrc2, err := runGen(t, "testdata/valid/specs")
	if err != nil {
		t.Fatalf("second run() error = %v", err)
	}
	if !bytes.Equal(rulesSrc1, rulesSrc2) {
		t.Error("generated rules file differs between two runs on identical specs")
	}
	if !bytes.Equal(fixturesSrc1, fixturesSrc2) {
		t.Error("generated fixtures file differs between two runs on identical specs")
	}
}

func TestDuplicateIDFails(t *testing.T) {
	_, _, err := runGen(t, "testdata/duplicate/specs")
	if err == nil {
		t.Fatal("run() error = nil, want an error for duplicate rule IDs")
	}
	if !strings.Contains(err.Error(), "dup-rule") {
		t.Errorf("error does not mention the duplicate ID %q: %v", "dup-rule", err)
	}
	if !strings.Contains(strings.ToLower(err.Error()), "duplicate") {
		t.Errorf("error does not mention 'duplicate': %v", err)
	}
}

func TestInvalidEnumFails(t *testing.T) {
	_, _, err := runGen(t, "testdata/badenum/specs")
	if err == nil {
		t.Fatal("run() error = nil, want an error for invalid minProfile enum")
	}
	if !strings.Contains(err.Error(), "minProfile") {
		t.Errorf("error does not mention 'minProfile': %v", err)
	}
	if !strings.Contains(err.Error(), "medium") {
		t.Errorf("error does not mention the bad value %q: %v", "medium", err)
	}
}

func TestMissingFixtureFails(t *testing.T) {
	_, _, err := runGen(t, "testdata/missingfixture/specs")
	if err == nil {
		t.Fatal("run() error = nil, want an error for a rule with no match fixtures")
	}
	if !strings.Contains(strings.ToLower(err.Error()), "match fixture") {
		t.Errorf("error does not mention missing match fixtures: %v", err)
	}
}

func TestNoOutputWrittenOnValidationFailure(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "zz_generated_rules.go")
	fixturesPath := filepath.Join(dir, "zz_generated_fixtures_test.go")

	if err := run("testdata/duplicate/specs", outPath, fixturesPath); err == nil {
		t.Fatal("run() error = nil, want error")
	}
	if _, err := os.Stat(outPath); !os.IsNotExist(err) {
		t.Errorf("expected no rules file to be written on failure, stat error = %v", err)
	}
	if _, err := os.Stat(fixturesPath); !os.IsNotExist(err) {
		t.Errorf("expected no fixtures file to be written on failure, stat error = %v", err)
	}
}

func TestDuplicateTriggerLiteralsAcrossRulesAreAllowed(t *testing.T) {
	// testdata/valid/specs deliberately has two rules ("zzz-last" in
	// a.json and "mmm-middle" in b.json) sharing the trigger literal
	// "zzz_". This must not be a validation error: the runtime automaton
	// dedupes triggers, and dispatch fans a hit out to every rule that
	// registered it.
	if _, _, err := runGen(t, "testdata/valid/specs"); err != nil {
		t.Fatalf("run() error = %v, want nil (duplicate trigger literals across rules must be allowed)", err)
	}
}
